//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class BillWisePayment
    {
        public long Id { get; set; }
        public string Type { get; set; }
        public Nullable<long> InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> ReceiptPaymentId { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Due { get; set; }
    
        public virtual PurchaseInvoice PurchaseInvoice { get; set; }
        public virtual ReceiptPayment ReceiptPayment { get; set; }
    }
    
}
