//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class BranchMaster
    {
        public BranchMaster()
        {
            this.CashTransfers = new HashSet<CashTransfer>();
            this.CashTransfers1 = new HashSet<CashTransfer>();
            this.ChickIssuedMasters = new HashSet<ChickIssuedMaster>();
            this.ChickReceivedMasters = new HashSet<ChickReceivedMaster>();
            this.ChickRequestHOMasters = new HashSet<ChickRequestHOMaster>();
            this.Departments = new HashSet<Department>();
            this.DEVouchers = new HashSet<DEVoucher>();
            this.Egg_HatcherySales_Hiss = new HashSet<Egg_HatcherySales_Hiss>();
            this.FarmMasters = new HashSet<FarmMaster>();
            this.FeedIssuedFromUnitMasters = new HashSet<FeedIssuedFromUnitMaster>();
            this.FeedIssuedMasters = new HashSet<FeedIssuedMaster>();
            this.FeedIssueHO_Master = new HashSet<FeedIssueHO_Master>();
            this.FeedReceivedFromFarmMasters = new HashSet<FeedReceivedFromFarmMaster>();
            this.FeedReceivedMasters = new HashSet<FeedReceivedMaster>();
            this.FeedReturnedMasters = new HashSet<FeedReturnedMaster>();
            this.FlockReceivedInFarmMasters = new HashSet<FlockReceivedInFarmMaster>();
            this.Hatchery_MSTR_Hiss = new HashSet<Hatchery_MSTR_Hiss>();
            this.MedicineIssuedMasters = new HashSet<MedicineIssuedMaster>();
            this.MedicineIssueHoMasters = new HashSet<MedicineIssueHoMaster>();
            this.MedicineReceivedMasters = new HashSet<MedicineReceivedMaster>();
            this.MedicineRequestMasters = new HashSet<MedicineRequestMaster>();
            this.MedicineReturnedMasters = new HashSet<MedicineReturnedMaster>();
            this.Received_Egg_Hiss = new HashSet<Received_Egg_Hiss>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ContactNumber { get; set; }
        public string EmailId { get; set; }
        public string Fax { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<CashTransfer> CashTransfers { get; set; }
        public virtual ICollection<CashTransfer> CashTransfers1 { get; set; }
        public virtual ICollection<ChickIssuedMaster> ChickIssuedMasters { get; set; }
        public virtual ICollection<ChickReceivedMaster> ChickReceivedMasters { get; set; }
        public virtual ICollection<ChickRequestHOMaster> ChickRequestHOMasters { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<DEVoucher> DEVouchers { get; set; }
        public virtual ICollection<Egg_HatcherySales_Hiss> Egg_HatcherySales_Hiss { get; set; }
        public virtual ICollection<FarmMaster> FarmMasters { get; set; }
        public virtual ICollection<FeedIssuedFromUnitMaster> FeedIssuedFromUnitMasters { get; set; }
        public virtual ICollection<FeedIssuedMaster> FeedIssuedMasters { get; set; }
        public virtual ICollection<FeedIssueHO_Master> FeedIssueHO_Master { get; set; }
        public virtual ICollection<FeedReceivedFromFarmMaster> FeedReceivedFromFarmMasters { get; set; }
        public virtual ICollection<FeedReceivedMaster> FeedReceivedMasters { get; set; }
        public virtual ICollection<FeedReturnedMaster> FeedReturnedMasters { get; set; }
        public virtual ICollection<FlockReceivedInFarmMaster> FlockReceivedInFarmMasters { get; set; }
        public virtual ICollection<Hatchery_MSTR_Hiss> Hatchery_MSTR_Hiss { get; set; }
        public virtual ICollection<MedicineIssuedMaster> MedicineIssuedMasters { get; set; }
        public virtual ICollection<MedicineIssueHoMaster> MedicineIssueHoMasters { get; set; }
        public virtual ICollection<MedicineReceivedMaster> MedicineReceivedMasters { get; set; }
        public virtual ICollection<MedicineRequestMaster> MedicineRequestMasters { get; set; }
        public virtual ICollection<MedicineReturnedMaster> MedicineReturnedMasters { get; set; }
        public virtual ICollection<Received_Egg_Hiss> Received_Egg_Hiss { get; set; }
    }
    
}
