//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class BRSALLBankBookView
    {
        public string ledgerID { get; set; }
        public string ledgerName { get; set; }
        public decimal PaymentAmount { get; set; }
        public decimal ReceiveAmount { get; set; }
        public decimal openingBal { get; set; }
        public Nullable<decimal> closingBal { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<int> fYearId { get; set; }
    }
    
}
