//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class BRSView
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string ledger { get; set; }
        public string ledgerName { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<decimal> ReceiveAmount { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> fYearId { get; set; }
        public Nullable<decimal> openingBal { get; set; }
        public string transactionType { get; set; }
        public Nullable<int> VoucherNo { get; set; }
    }
    
}
