//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class CashTransfer
    {
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public string DateString { get; set; }
        public int FromUnit { get; set; }
        public int ToUnit { get; set; }
        public int CashLedger { get; set; }
        public int CashTransferLedger { get; set; }
        public decimal CashAmount { get; set; }
        public string Remarks { get; set; }
        public long Serial { get; set; }
        public string NO { get; set; }
        public int FinancialYearId { get; set; }
        public bool Approved { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int BranchId { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual BranchMaster BranchMaster1 { get; set; }
    }
    
}
