//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class CategoryUSA
    {
        public CategoryUSA()
        {
            this.CategoryUSA1 = new HashSet<CategoryUSA>();
            this.TransactionUSADetails = new HashSet<TransactionUSADetail>();
            this.TransactionUSADetails1 = new HashSet<TransactionUSADetail>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> ParentGroupId { get; set; }
        public string CategoryType { get; set; }
        public Nullable<long> CategoryTypeId { get; set; }
        public long UserId { get; set; }
        public long BranchId { get; set; }
        public long CompanyId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<CategoryUSA> CategoryUSA1 { get; set; }
        public virtual CategoryUSA CategoryUSA2 { get; set; }
        public virtual ICollection<TransactionUSADetail> TransactionUSADetails { get; set; }
        public virtual ICollection<TransactionUSADetail> TransactionUSADetails1 { get; set; }
    }
    
}
