//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class CheckDescriptoinMaster
    {
        public long Id { get; set; }
        public string CheckDescription { get; set; }
        public Nullable<int> CheckId { get; set; }
    
        public virtual CheckMaster CheckMaster { get; set; }
    }
    
}
