//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class ChickIssuedMaster
    {
        public int Id { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string ChallanNo { get; set; }
        public Nullable<int> ChicksPlaced_HO_ { get; set; }
        public Nullable<decimal> RatePerChick { get; set; }
        public string QualityofChicken { get; set; }
        public Nullable<decimal> ChicksWeight { get; set; }
        public string HatcheryCode { get; set; }
        public string HatcheryName { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public System.DateTime DateOfDespatch { get; set; }
        public string DateOfDespatchString { get; set; }
        public string LineSupervisorName { get; set; }
        public string LineSupervisorcode { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
    }
    
}
