//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class CompanyHead
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Userid { get; set; }
        public string CompanyDisplayName { get; set; }
        public string CompanyLogo { get; set; }
        public string BusinessLine { get; set; }
        public string CompanyType { get; set; }
        public string CompanyDescription { get; set; }
        public string CurrencyId { get; set; }
        public string GST_VATNumber { get; set; }
        public string TANNO { get; set; }
        public string ROC { get; set; }
        public string TIN { get; set; }
        public string PANNO { get; set; }
        public string Website { get; set; }
        public string PurchaseEmailId { get; set; }
        public string SalesEmailId { get; set; }
        public string Fax { get; set; }
        public string CountryId { get; set; }
        public string StateId { get; set; }
        public string City { get; set; }
        public string Zipcode { get; set; }
        public string Address { get; set; }
        public string PostalCountryId { get; set; }
        public string PostalStateId { get; set; }
        public string PostalCity { get; set; }
        public string PostalZipcode { get; set; }
        public string PostalAddress { get; set; }
        public Nullable<bool> IssamepostalAddress { get; set; }
        public string ContactNumber { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Dateformat { get; set; }
    }
    
}
