//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class CompanySetupGuide
    {
        public long Id { get; set; }
        public bool Start { get; set; }
        public bool Organization { get; set; }
        public bool Financial { get; set; }
        public bool Accounts { get; set; }
        public bool Done { get; set; }
        public long CompanyId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public long UserId { get; set; }
    }
    
}
