//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Composition
    {
        public Composition()
        {
            this.ProductCompositions = new HashSet<ProductComposition>();
        }
    
        public long Id { get; set; }
        public string Alphabet { get; set; }
    
        public virtual ICollection<ProductComposition> ProductCompositions { get; set; }
    }
    
}
