//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Contra
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int fYearId { get; set; }
        public int BranchId { get; set; }
        public int CompanyId { get; set; }
        public string Type { get; set; }
        public int ToId { get; set; }
        public int FromId { get; set; }
        public string chequeNo { get; set; }
        public Nullable<System.DateTime> chequeDate { get; set; }
        public decimal Amount { get; set; }
        public string transactionType { get; set; }
        public string transactionNo { get; set; }
        public string Remarks { get; set; }
        public int VoucherNo { get; set; }
    }
    
}
