//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Costing
    {
        public Costing()
        {
            this.PurchaseCostingDetails = new HashSet<PurchaseCostingDetail>();
            this.SalesCostingDetails = new HashSet<SalesCostingDetail>();
            this.SalesPerformaCostingDetails = new HashSet<SalesPerformaCostingDetail>();
        }
    
        public long Id { get; set; }
        public long LId { get; set; }
        public string Name { get; set; }
        public string TransactionType { get; set; }
        public string Type { get; set; }
        public long UserId { get; set; }
        public long CompanyId { get; set; }
        public long BranchId { get; set; }
    
        public virtual LedgerMaster LedgerMaster { get; set; }
        public virtual ICollection<PurchaseCostingDetail> PurchaseCostingDetails { get; set; }
        public virtual ICollection<SalesCostingDetail> SalesCostingDetails { get; set; }
        public virtual ICollection<SalesPerformaCostingDetail> SalesPerformaCostingDetails { get; set; }
    }
    
}
