//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Country
    {
        public Country()
        {
            this.Plants = new HashSet<Plant>();
        }
    
        public long CountryId { get; set; }
        public int Code { get; set; }
        public string Country1 { get; set; }
    
        public virtual ICollection<Plant> Plants { get; set; }
    }
    
}
