//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class CurrencyRate
    {
        public CurrencyRate()
        {
            this.Customers = new HashSet<Customer>();
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public long Id { get; set; }
        public int CurrencyId { get; set; }
        public decimal PurchaseRate { get; set; }
        public decimal SellRate { get; set; }
        public Nullable<bool> IsBaseCurrency { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public long CompanyId { get; set; }
        public long UserId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
    }
    
}
