//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Currency
    {
        public Currency()
        {
            this.Companies = new HashSet<Company>();
            this.CurrencyRates = new HashSet<CurrencyRate>();
            this.PurchaseInvoices = new HashSet<PurchaseInvoice>();
            this.PurchaseInvoices1 = new HashSet<PurchaseInvoice>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.PurchaseOrders1 = new HashSet<PurchaseOrder>();
            this.PurchaseReceipts = new HashSet<PurchaseReceipt>();
            this.PurchaseReceipts1 = new HashSet<PurchaseReceipt>();
            this.PurchaseReturns = new HashSet<PurchaseReturn>();
            this.PurchaseReturns1 = new HashSet<PurchaseReturn>();
            this.SalesDeliveries = new HashSet<SalesDelivery>();
            this.SalesDeliveries1 = new HashSet<SalesDelivery>();
            this.SalesInvoices = new HashSet<SalesInvoice>();
            this.SalesInvoices1 = new HashSet<SalesInvoice>();
            this.SalesOrders = new HashSet<SalesOrder>();
            this.SalesOrders1 = new HashSet<SalesOrder>();
            this.SalesPerformaInvoices = new HashSet<SalesPerformaInvoice>();
            this.SalesPerformaInvoices1 = new HashSet<SalesPerformaInvoice>();
            this.SalesQuotes = new HashSet<SalesQuote>();
            this.SalesQuotes1 = new HashSet<SalesQuote>();
            this.SalesReturns = new HashSet<SalesReturn>();
            this.SalesReturns1 = new HashSet<SalesReturn>();
        }
    
        public int CurrencyId { get; set; }
        public string Country { get; set; }
        public string Currency1 { get; set; }
        public string ISO_4217 { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<CurrencyRate> CurrencyRates { get; set; }
        public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual ICollection<PurchaseInvoice> PurchaseInvoices1 { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders1 { get; set; }
        public virtual ICollection<PurchaseReceipt> PurchaseReceipts { get; set; }
        public virtual ICollection<PurchaseReceipt> PurchaseReceipts1 { get; set; }
        public virtual ICollection<PurchaseReturn> PurchaseReturns { get; set; }
        public virtual ICollection<PurchaseReturn> PurchaseReturns1 { get; set; }
        public virtual ICollection<SalesDelivery> SalesDeliveries { get; set; }
        public virtual ICollection<SalesDelivery> SalesDeliveries1 { get; set; }
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
        public virtual ICollection<SalesInvoice> SalesInvoices1 { get; set; }
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
        public virtual ICollection<SalesOrder> SalesOrders1 { get; set; }
        public virtual ICollection<SalesPerformaInvoice> SalesPerformaInvoices { get; set; }
        public virtual ICollection<SalesPerformaInvoice> SalesPerformaInvoices1 { get; set; }
        public virtual ICollection<SalesQuote> SalesQuotes { get; set; }
        public virtual ICollection<SalesQuote> SalesQuotes1 { get; set; }
        public virtual ICollection<SalesReturn> SalesReturns { get; set; }
        public virtual ICollection<SalesReturn> SalesReturns1 { get; set; }
    }
    
}
