//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Customer
    {
        public Customer()
        {
            this.SalesDeliveries = new HashSet<SalesDelivery>();
            this.SalesInvoices = new HashSet<SalesInvoice>();
            this.SalesOrders = new HashSet<SalesOrder>();
            this.SalesPerformaInvoices = new HashSet<SalesPerformaInvoice>();
            this.SalesQuotes = new HashSet<SalesQuote>();
            this.SalesReturns = new HashSet<SalesReturn>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string CustomerType { get; set; }
        public Nullable<long> WarehouseId { get; set; }
        public long LId { get; set; }
        public Nullable<long> PId { get; set; }
        public string PCode { get; set; }
        public decimal Discount { get; set; }
        public Nullable<decimal> OpeningBal { get; set; }
        public bool IsFDCompounded { get; set; }
        public decimal FD1 { get; set; }
        public decimal FD2 { get; set; }
        public decimal FD3 { get; set; }
        public decimal FD4 { get; set; }
        public string GstVatNumber { get; set; }
        public string PanNo { get; set; }
        public string TinNo { get; set; }
        public string ServiceTaxNo { get; set; }
        public string Notes { get; set; }
        public bool Taxable { get; set; }
        public long TaxId { get; set; }
        public long CurrencyId { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string BankAccount { get; set; }
        public Nullable<int> PaymentTerm { get; set; }
        public string Website { get; set; }
        public string PoCountry { get; set; }
        public string PoAddressName { get; set; }
        public string PoStreetPoBox { get; set; }
        public string PoSuburb { get; set; }
        public string PoCity { get; set; }
        public string PoStateRegion { get; set; }
        public string PoPostalCode { get; set; }
        public string AddressName { get; set; }
        public string StreetPoBox { get; set; }
        public string Suburb { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string StateRegion { get; set; }
        public string PostalCode { get; set; }
        public string DelCountry { get; set; }
        public string DelAddressName { get; set; }
        public string DelStreetPoBox { get; set; }
        public string DelSuburb { get; set; }
        public string DelCity { get; set; }
        public string DelStateRegion { get; set; }
        public string DelPostalCode { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public string ContactOfficePhone { get; set; }
        public string ContactWebsite { get; set; }
        public string ContactPhone { get; set; }
        public string ContactFaxNo { get; set; }
        public string ContactMobile { get; set; }
        public string ContactDDINumber { get; set; }
        public string ContactTollFreeNo { get; set; }
        public long UserId { get; set; }
        public long CompanyId { get; set; }
        public long BranchId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SalesPersonId { get; set; }
    
        public virtual CurrencyRate CurrencyRate { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<SalesDelivery> SalesDeliveries { get; set; }
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
        public virtual ICollection<SalesPerformaInvoice> SalesPerformaInvoices { get; set; }
        public virtual ICollection<SalesQuote> SalesQuotes { get; set; }
        public virtual ICollection<SalesReturn> SalesReturns { get; set; }
    }
    
}
