//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class DailyCheck
    {
        public long Id { get; set; }
        public Nullable<long> DailyEntryId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string DateString { get; set; }
        public long CheckId { get; set; }
        public Nullable<long> CheckDescriptionId { get; set; }
        public Nullable<long> FlockId { get; set; }
        public Nullable<bool> Ischecked { get; set; }
    }
    
}
