//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class DailyAttendance
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Shift { get; set; }
        public Nullable<System.TimeSpan> SIT { get; set; }
        public Nullable<System.TimeSpan> SOT { get; set; }
        public Nullable<System.TimeSpan> AIT { get; set; }
        public Nullable<System.TimeSpan> AOT { get; set; }
        public Nullable<System.TimeSpan> WDur { get; set; }
        public Nullable<System.TimeSpan> OT { get; set; }
        public Nullable<System.TimeSpan> Total { get; set; }
        public Nullable<System.TimeSpan> LB { get; set; }
        public Nullable<System.TimeSpan> EG { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public System.DateTime AttendanceDate { get; set; }
    }
    
}
