//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class DateCultureFormat1
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string ShortDatePattern { get; set; }
        public string ShortDatePatternLower { get; set; }
        public string ShortTimePattern { get; set; }
        public bool IsDeleted { get; set; }
    }
    
}
