//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class DEBankDetail
    {
        public long Id { get; set; }
        public long DEVId { get; set; }
        public long LID { get; set; }
        public string Mode { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string ChequeDetail { get; set; }
    
        public virtual DEVoucher DEVoucher { get; set; }
        public virtual LedgerMaster LedgerMaster { get; set; }
    }
    
}
