//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class DEVoucher
    {
        public DEVoucher()
        {
            this.DEBankDetails = new HashSet<DEBankDetail>();
            this.DEVoucherDetails = new HashSet<DEVoucherDetail>();
        }
    
        public long Id { get; set; }
        public string DEVNO { get; set; }
        public long DEVSerial { get; set; }
        public short DEVType { get; set; }
        public string Narration { get; set; }
        public System.DateTime DEVDate { get; set; }
        public short FinancialYearId { get; set; }
        public short CompanyId { get; set; }
        public short UserId { get; set; }
        public int BranchId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<short> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual ICollection<DEBankDetail> DEBankDetails { get; set; }
        public virtual ICollection<DEVoucherDetail> DEVoucherDetails { get; set; }
    }
    
}
