//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class DEVoucherDetail
    {
        public long Id { get; set; }
        public long DEVId { get; set; }
        public int Club { get; set; }
        public long LID { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public bool IsBank { get; set; }
    
        public virtual DEVoucher DEVoucher { get; set; }
        public virtual LedgerMaster LedgerMaster { get; set; }
    }
    
}
