//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Egg_Candling_Hiss
    {
        public Egg_Candling_Hiss()
        {
            this.Egg_HatcherySales_Hiss = new HashSet<Egg_HatcherySales_Hiss>();
        }
    
        public long Id { get; set; }
        public Nullable<long> SettingId { get; set; }
        public Nullable<System.DateTime> CandlingDate { get; set; }
        public Nullable<long> InfertileEgg { get; set; }
        public Nullable<long> BastingEgg { get; set; }
        public Nullable<long> DeadInShell { get; set; }
        public Nullable<long> DeadChicks { get; set; }
        public Nullable<long> SaleableChicks { get; set; }
        public Nullable<long> NonSaleableChicks { get; set; }
        public Nullable<long> SaledChicks { get; set; }
        public Nullable<long> SemiChicks { get; set; }
        public Nullable<long> CullChicks { get; set; }
        public Nullable<long> PippedEgg { get; set; }
        public Nullable<long> SampleEgg { get; set; }
        public Nullable<decimal> TenDaysPercentage { get; set; }
        public Nullable<long> TenDays_Infertile { get; set; }
        public Nullable<long> EighteenDays_Infertile { get; set; }
        public Nullable<long> EighteenDays_Basting { get; set; }
        public Nullable<decimal> AvgWt { get; set; }
    
        public virtual Egg_Setting_Hiss Egg_Setting_Hiss { get; set; }
        public virtual ICollection<Egg_HatcherySales_Hiss> Egg_HatcherySales_Hiss { get; set; }
    }
    
}
