//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Egg_HatcherySales_Hiss
    {
        public long Id { get; set; }
        public Nullable<long> Candling_Id { get; set; }
        public Nullable<System.DateTime> DespatchDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<long> PartyId { get; set; }
        public string PartyName { get; set; }
        public string HandChallanNo { get; set; }
        public string VehicleNo { get; set; }
        public string DeliveryManNo { get; set; }
        public string DeliveryManName { get; set; }
        public Nullable<long> ChicksQuantity { get; set; }
        public Nullable<long> BoxQuantity { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> FyearId { get; set; }
        public string SystemChallanNo { get; set; }
        public Nullable<long> ChallanId { get; set; }
        public Nullable<long> HatcheryId { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual Egg_Candling_Hiss Egg_Candling_Hiss { get; set; }
    }
    
}
