//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Egg_Setting_Hiss
    {
        public Egg_Setting_Hiss()
        {
            this.Egg_Candling_Hiss = new HashSet<Egg_Candling_Hiss>();
        }
    
        public long Id { get; set; }
        public string SettingNo { get; set; }
        public Nullable<System.DateTime> DateOfSetting { get; set; }
        public string TimeOfSetting { get; set; }
        public Nullable<long> ReceivedId { get; set; }
        public Nullable<long> EggQuantity { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public bool IsCandellingDone { get; set; }
        public Nullable<long> SettingEgg { get; set; }
        public Nullable<long> InfertileEgg { get; set; }
        public Nullable<long> EggLost { get; set; }
        public Nullable<long> BrockenEgg { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public bool SendMail { get; set; }
    
        public virtual ICollection<Egg_Candling_Hiss> Egg_Candling_Hiss { get; set; }
        public virtual Received_Egg_Hiss Received_Egg_Hiss { get; set; }
    }
    
}
