//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class EggFarm_MSTR_Hiss
    {
        public EggFarm_MSTR_Hiss()
        {
            this.EggFarm_Flock_Hiss = new HashSet<EggFarm_Flock_Hiss>();
            this.Received_Egg_Hiss = new HashSet<Received_Egg_Hiss>();
        }
    
        public long Id { get; set; }
        public string FarmName { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Address { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
    
        public virtual ICollection<EggFarm_Flock_Hiss> EggFarm_Flock_Hiss { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<Received_Egg_Hiss> Received_Egg_Hiss { get; set; }
    }
    
}
