//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Emp_Department
    {
        public int id { get; set; }
        public string EmpCode { get; set; }
        public string DeptCode { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> insertDate { get; set; }
        public Nullable<int> DeptHead { get; set; }
    }
    
}
