//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class EmpDocument
    {
        public int Id { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public string EmployeeId { get; set; }
        public string DocUrl { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public long UserId { get; set; }
        public long CompanyId { get; set; }
        public long BranchId { get; set; }
    
        public virtual EmpDocument EmpDocument1 { get; set; }
        public virtual EmpDocument EmpDocument2 { get; set; }
    }
    
}
