//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class EmployeeLeave
    {
        public int EmployeeLeaveId { get; set; }
        public string EmployeeId { get; set; }
        public int LeaveId { get; set; }
        public Nullable<int> TotalLeave { get; set; }
        public Nullable<int> LeaveUsed { get; set; }
        public Nullable<int> LeaveLeft { get; set; }
        public Nullable<int> fYearID { get; set; }
    }
    
}
