//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Employeecursor
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public int Salary { get; set; }
        public string Address { get; set; }
    }
    
}
