//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Employee
    {
        public Employee()
        {
            this.Plants = new HashSet<Plant>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int EmployeeTypeID { get; set; }
        public int DesignationID { get; set; }
        public int GradeID { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string PresentState { get; set; }
        public string PresentPIN { get; set; }
        public string PresentCity { get; set; }
        public string PermanentState { get; set; }
        public string PermanentCity { get; set; }
        public string PermanentPIN { get; set; }
        public bool IsSamePresentAddress { get; set; }
        public string PAN { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string AltPhone { get; set; }
        public string Email { get; set; }
        public string MaritialStatus { get; set; }
        public string Sex { get; set; }
        public string Qualification { get; set; }
        public string Specialization { get; set; }
        public string Experience { get; set; }
        public string PreCompany { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string PFNo { get; set; }
        public string BankAccntNo { get; set; }
        public string ESICNo { get; set; }
        public string empPhoto { get; set; }
        public Nullable<int> EmpIDProf { get; set; }
        public string EmpIDProfNo { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public long userId { get; set; }
        public long companyid { get; set; }
        public long BranchId { get; set; }
        public string DateOfBirth { get; set; }
    
        public virtual Designation Designation { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual ICollection<Plant> Plants { get; set; }
    }
    
}
