//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class ExpensesHeadMaster
    {
        public ExpensesHeadMaster()
        {
            this.VoucherPolitries = new HashSet<VoucherPolitry>();
        }
    
        public int Id { get; set; }
        public string ExpenseHead { get; set; }
    
        public virtual ICollection<VoucherPolitry> VoucherPolitries { get; set; }
    }
    
}
