//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class FarmerReportSalesDetail
    {
        public long Id { get; set; }
        public Nullable<long> PartyId { get; set; }
        public string PartyName { get; set; }
        public Nullable<int> FarmerReportId { get; set; }
        public Nullable<long> FlockId { get; set; }
        public string FlockCode { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> PriceRate { get; set; }
        public Nullable<long> NoOfBirds { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual FarmerReport FarmerReport { get; set; }
        public virtual Product Product { get; set; }
    }
    
}
