//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class FarmDailyEntryDetail
    {
        public long Id { get; set; }
        public long FarmDailyEntryId { get; set; }
        public long ProductId { get; set; }
        public Nullable<decimal> ProductSize { get; set; }
        public decimal ConsumedQuantity { get; set; }
        public Nullable<int> Source { get; set; }
    
        public virtual FarmDailyEntry FarmDailyEntry { get; set; }
        public virtual Product Product { get; set; }
    }
    
}
