//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class FarmDailyEntry
    {
        public FarmDailyEntry()
        {
            this.FarmDailyEntryDetails = new HashSet<FarmDailyEntryDetail>();
        }
    
        public long Id { get; set; }
        public int FlockId { get; set; }
        public int LinesManId { get; set; }
        public System.DateTime Date { get; set; }
        public int ExcessBird { get; set; }
        public int Mortality { get; set; }
        public string ReasonForDeath { get; set; }
        public Nullable<decimal> AvgWt { get; set; }
        public Nullable<decimal> TotalBodyWeightClosing { get; set; }
        public string Remarks { get; set; }
        public int FinancialYearid { get; set; }
        public int BranchId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> Source { get; set; }
        public string ChickPhoto { get; set; }
        public string ChickVideo { get; set; }
        public Nullable<long> Reason_Id { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Place { get; set; }
        public Nullable<long> VisitType { get; set; }
    
        public virtual ICollection<FarmDailyEntryDetail> FarmDailyEntryDetails { get; set; }
    }
    
}
