//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class FarmerReportFeedDetail
    {
        public long Id { get; set; }
        public Nullable<int> FarmerReportId { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> UnitId { get; set; }
        public Nullable<decimal> UnitFormula { get; set; }
        public Nullable<decimal> PriceRate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> LastOpeningQuantity { get; set; }
        public Nullable<decimal> LeftQuantity { get; set; }
        public Nullable<decimal> TotalConsumedQuantity { get; set; }
        public Nullable<decimal> ConsumedQuantity { get; set; }
        public string Description { get; set; }
    
        public virtual FarmerReport FarmerReport { get; set; }
    }
    
}
