//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class FarmMaster
    {
        public FarmMaster()
        {
            this.ChickRequestHOMasters = new HashSet<ChickRequestHOMaster>();
            this.FeedIssuedFromUnitMasters = new HashSet<FeedIssuedFromUnitMaster>();
            this.FeedIssueHO_Master = new HashSet<FeedIssueHO_Master>();
            this.FeedReceivedFromFarmMasters = new HashSet<FeedReceivedFromFarmMaster>();
            this.FeedReturnedMasters = new HashSet<FeedReturnedMaster>();
            this.FlockReceivedInFarmMasters = new HashSet<FlockReceivedInFarmMaster>();
            this.MedicineIssuedMasters = new HashSet<MedicineIssuedMaster>();
            this.MedicineIssueHoMasters = new HashSet<MedicineIssueHoMaster>();
            this.MedicineReceivedMasters = new HashSet<MedicineReceivedMaster>();
            this.MedicineRequestMasters = new HashSet<MedicineRequestMaster>();
            this.MedicineReturnedMasters = new HashSet<MedicineReturnedMaster>();
            this.PoultryDailyEntries = new HashSet<PoultryDailyEntry>();
            this.SectionMasters = new HashSet<SectionMaster>();
            this.UploadImageMasters = new HashSet<UploadImageMaster>();
        }
    
        public int Id { get; set; }
        public string FarmName { get; set; }
        public string FarmCode { get; set; }
        public Nullable<int> FarmUnitId { get; set; }
        public string FarmerName { get; set; }
        public string FarmerCode { get; set; }
        public string FarmerAddress { get; set; }
        public string FarmerHouseNo { get; set; }
        public string FarmerContactNo { get; set; }
        public string Area { get; set; }
        public string Location { get; set; }
        public string Dist { get; set; }
        public string State { get; set; }
        public string Village { get; set; }
        public string Address { get; set; }
        public Nullable<int> NoOfPen { get; set; }
        public Nullable<decimal> PenSize { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string FarmsImagePath { get; set; }
        public string FarmersImagePath { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual ICollection<ChickRequestHOMaster> ChickRequestHOMasters { get; set; }
        public virtual ICollection<FeedIssuedFromUnitMaster> FeedIssuedFromUnitMasters { get; set; }
        public virtual ICollection<FeedIssueHO_Master> FeedIssueHO_Master { get; set; }
        public virtual ICollection<FeedReceivedFromFarmMaster> FeedReceivedFromFarmMasters { get; set; }
        public virtual ICollection<FeedReturnedMaster> FeedReturnedMasters { get; set; }
        public virtual ICollection<FlockReceivedInFarmMaster> FlockReceivedInFarmMasters { get; set; }
        public virtual ICollection<MedicineIssuedMaster> MedicineIssuedMasters { get; set; }
        public virtual ICollection<MedicineIssueHoMaster> MedicineIssueHoMasters { get; set; }
        public virtual ICollection<MedicineReceivedMaster> MedicineReceivedMasters { get; set; }
        public virtual ICollection<MedicineRequestMaster> MedicineRequestMasters { get; set; }
        public virtual ICollection<MedicineReturnedMaster> MedicineReturnedMasters { get; set; }
        public virtual ICollection<PoultryDailyEntry> PoultryDailyEntries { get; set; }
        public virtual ICollection<SectionMaster> SectionMasters { get; set; }
        public virtual ICollection<UploadImageMaster> UploadImageMasters { get; set; }
    }
    
}
