//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class FarmerReport
    {
        public FarmerReport()
        {
            this.FarmerReportFeedDetails = new HashSet<FarmerReportFeedDetail>();
            this.FarmerReportSalesDetails = new HashSet<FarmerReportSalesDetail>();
        }
    
        public int Id { get; set; }
        public string FarmerName { get; set; }
        public string Address { get; set; }
        public string SupervisorName { get; set; }
        public Nullable<System.DateTime> DateofPlacement { get; set; }
        public string DateOfPlacementString { get; set; }
        public Nullable<long> FlockId { get; set; }
        public string FlockCode { get; set; }
        public Nullable<System.DateTime> FlockEndDate { get; set; }
        public string FlockEndDateString { get; set; }
        public Nullable<decimal> AgeOfChicks { get; set; }
        public Nullable<long> NoOfChicks { get; set; }
        public Nullable<long> NoOfBirdsSold { get; set; }
        public Nullable<long> NoOfChicksLeft { get; set; }
        public Nullable<decimal> MortalityOfBirds { get; set; }
        public Nullable<decimal> ShortageOfBirds { get; set; }
        public Nullable<decimal> FeedRecieved { get; set; }
        public Nullable<decimal> FeedReturn { get; set; }
        public Nullable<decimal> ChicksCost { get; set; }
        public Nullable<decimal> ChikRateCost { get; set; }
        public string ChickRateType { get; set; }
        public Nullable<decimal> MurgirRateForFarmer { get; set; }
        public Nullable<decimal> MurgirDamForFarmer { get; set; }
        public Nullable<decimal> FeedCost { get; set; }
        public Nullable<decimal> FeedRateCost { get; set; }
        public string FeedRateType { get; set; }
        public Nullable<decimal> FeedRateForFarmer { get; set; }
        public Nullable<decimal> KhabarKhorochForFarmer { get; set; }
        public Nullable<decimal> MedicineCost { get; set; }
        public string MedicineType { get; set; }
        public Nullable<decimal> MedicineCostActual { get; set; }
        public Nullable<decimal> MedicineRateForFarmer { get; set; }
        public Nullable<decimal> MedicineKhorochForFarmer { get; set; }
        public Nullable<decimal> OverHeadCost { get; set; }
        public string OverheadType { get; set; }
        public Nullable<decimal> StandarCost { get; set; }
        public string StandardCostType { get; set; }
        public Nullable<decimal> TotalChickCost { get; set; }
        public Nullable<decimal> TotalFeedMedicineCost { get; set; }
        public Nullable<decimal> TotalOverHeadCost { get; set; }
        public Nullable<decimal> TotalProductionCost { get; set; }
        public Nullable<decimal> ProductionCostPerKG { get; set; }
        public Nullable<decimal> AvgSaleRate { get; set; }
        public Nullable<decimal> GrowingChargefixed { get; set; }
        public string GrowingChargeFixedType { get; set; }
        public Nullable<decimal> GrowingCharge { get; set; }
        public Nullable<decimal> TotalGrowingCharge { get; set; }
        public Nullable<decimal> TotalGrowingChargeFixed { get; set; }
        public Nullable<decimal> RateBonus { get; set; }
        public string RateBonusType { get; set; }
        public Nullable<decimal> TotalRateBonus { get; set; }
        public Nullable<decimal> ShortageOfBirdsDeduction { get; set; }
        public Nullable<decimal> NetGrowingCharge { get; set; }
    
        public virtual ICollection<FarmerReportFeedDetail> FarmerReportFeedDetails { get; set; }
        public virtual ICollection<FarmerReportSalesDetail> FarmerReportSalesDetails { get; set; }
    }
    
}
