//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class FeedMaster
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ChequeNo { get; set; }
        public string Particulars { get; set; }
        public string FeedType { get; set; }
        public Nullable<int> FeedPlantCode { get; set; }
        public Nullable<int> FeedPlantNoOfBagsReceived { get; set; }
        public Nullable<decimal> FeedPlantTotalWeightReceived { get; set; }
        public Nullable<decimal> FeedPlantCumulativeWeightReceived { get; set; }
        public string FeedPlantReceivedTagNo { get; set; }
        public Nullable<int> FeedPlantNoOfBagsIssued { get; set; }
        public Nullable<decimal> FeedPlantTotalWeightIssued { get; set; }
        public Nullable<decimal> FeedPlantCumulativeWeightIssued { get; set; }
        public string FeedPlantIssuedTagNo { get; set; }
        public Nullable<int> FeedPlantNoOfBagsBalance { get; set; }
        public Nullable<decimal> FeedPlantTotalWeightBalance { get; set; }
        public Nullable<decimal> FeedPlantCumulativeWeightBalance { get; set; }
        public string FeedPlantBalanceTagNo { get; set; }
        public Nullable<int> DelimarymanId { get; set; }
        public byte[] SignatureOfDeliveryMan { get; set; }
        public Nullable<int> FarmerId { get; set; }
        public byte[] SignatureOfFarmer { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
    
}
