//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class FeedIssueHO_Master
    {
        public int Id { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> FarmId { get; set; }
        public string FeedType { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public Nullable<int> Bags { get; set; }
        public string ChallanNo { get; set; }
        public string DeliveryManCode { get; set; }
        public string DeliveryManName { get; set; }
        public Nullable<decimal> Loose { get; set; }
        public Nullable<decimal> TotalFeeds { get; set; }
        public string Tagno { get; set; }
        public string SignatureOfDeliveryMan { get; set; }
        public string Signature { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual FarmMaster FarmMaster { get; set; }
    }
    
}
