//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class FeedReceivedDetail
    {
        public FeedReceivedDetail()
        {
            this.FeedIssuedFromUnitDetails = new HashSet<FeedIssuedFromUnitDetail>();
        }
    
        public long Id { get; set; }
        public int FeedReceivedMasterId { get; set; }
        public string FeedReceivedChallanNo { get; set; }
        public long CategoryId { get; set; }
        public long ProductId { get; set; }
        public long UnitId { get; set; }
        public Nullable<decimal> UnitFormula { get; set; }
        public Nullable<decimal> PriceRate { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> IssuedQuantity { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public string DateofIssueString { get; set; }
        public Nullable<System.DateTime> DateOfReceive { get; set; }
        public string DateOfReceiveString { get; set; }
        public string Description { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<FeedIssuedFromUnitDetail> FeedIssuedFromUnitDetails { get; set; }
        public virtual FeedReceivedMaster FeedReceivedMaster { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductCategory_MSTR ProductCategory_MSTR { get; set; }
        public virtual UOM UOM { get; set; }
    }
    
}
