//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class FeedIssuedMaster
    {
        public FeedIssuedMaster()
        {
            this.FeedIssueDetails = new HashSet<FeedIssueDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string FeedType { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public string DateOfIssueString { get; set; }
        public string Status { get; set; }
        public string ChallanNo { get; set; }
        public string DeliveryManCode { get; set; }
        public string DeliveryManName { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual ICollection<FeedIssueDetail> FeedIssueDetails { get; set; }
    }
    
}
