//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class FeedReturnedMaster
    {
        public FeedReturnedMaster()
        {
            this.FeedReturnedFromFarmDetails = new HashSet<FeedReturnedFromFarmDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> FarmId { get; set; }
        public Nullable<int> FlockId { get; set; }
        public string FeedType { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public string DateOfIssueString { get; set; }
        public string ChallanNo { get; set; }
        public string DeliveryManCode { get; set; }
        public string DeliveryManName { get; set; }
        public string SignatureOfDeliveryMan { get; set; }
        public string Signature { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Status { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual FarmMaster FarmMaster { get; set; }
        public virtual ICollection<FeedReturnedFromFarmDetail> FeedReturnedFromFarmDetails { get; set; }
        public virtual FlockReceivedInFarmMaster FlockReceivedInFarmMaster { get; set; }
    }
    
}
