//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class FeedIssueDetail
    {
        public long Id { get; set; }
        public int FeedIssueMasterId { get; set; }
        public long CategoryId { get; set; }
        public long ProductId { get; set; }
        public long UnitId { get; set; }
        public Nullable<decimal> UnitFormula { get; set; }
        public Nullable<decimal> PriceRate { get; set; }
        public decimal Quantity { get; set; }
        public string Description { get; set; }
    
        public virtual FeedIssuedMaster FeedIssuedMaster { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductCategory_MSTR ProductCategory_MSTR { get; set; }
        public virtual UOM UOM { get; set; }
    }
    
}
