//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class FlockMaster
    {
        public int Id { get; set; }
        public int ShedId { get; set; }
        public string FlockCode { get; set; }
        public Nullable<long> AvailableChicks { get; set; }
        public string QualityOfChicken { get; set; }
        public Nullable<decimal> ChicksWeight { get; set; }
        public Nullable<decimal> PriceRate { get; set; }
        public bool Status { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> LineSupervisorId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ShedMaster ShedMaster { get; set; }
    }
    
}
