//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class FlockReceivedInFarmMaster
    {
        public FlockReceivedInFarmMaster()
        {
            this.FeedReceivedFromFarmMasters = new HashSet<FeedReceivedFromFarmMaster>();
            this.FeedReturnedMasters = new HashSet<FeedReturnedMaster>();
            this.PoultryDailyEntries = new HashSet<PoultryDailyEntry>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FarmId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string FlockCode { get; set; }
        public string ChallanNo { get; set; }
        public string ReceivedChallanNo { get; set; }
        public Nullable<long> AvailableChicks { get; set; }
        public Nullable<decimal> PriceRate { get; set; }
        public Nullable<int> ChicksReceived { get; set; }
        public Nullable<int> ShortageOfChicks { get; set; }
        public string QualityOfChicken { get; set; }
        public Nullable<decimal> ChicksWeight { get; set; }
        public bool Status { get; set; }
        public System.DateTime DateOfReceive { get; set; }
        public string DateOfReceiveString { get; set; }
        public string LineSupervisorName { get; set; }
        public string LineSupervisorCode { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual FarmMaster FarmMaster { get; set; }
        public virtual ICollection<FeedReceivedFromFarmMaster> FeedReceivedFromFarmMasters { get; set; }
        public virtual ICollection<FeedReturnedMaster> FeedReturnedMasters { get; set; }
        public virtual ICollection<PoultryDailyEntry> PoultryDailyEntries { get; set; }
    }
    
}
