//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class FurtherDiscount
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Discount { get; set; }
        public Nullable<bool> FD1 { get; set; }
        public Nullable<bool> FD2 { get; set; }
        public Nullable<bool> FD3 { get; set; }
        public Nullable<bool> FD4 { get; set; }
        public long CompanyId { get; set; }
        public long UserId { get; set; }
        public long BranchId { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public bool IsDeleted { get; set; }
    }
    
}
