//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class GeneralHoliday
    {
        public int GeneralHolidayId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Day { get; set; }
        public string Remarks { get; set; }
        public string Type { get; set; }
        public Nullable<int> fYearID { get; set; }
    }
    
}
