//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Grade
    {
        public Grade()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int GradeId { get; set; }
        public string GradeName { get; set; }
        public Nullable<decimal> MinSal { get; set; }
        public Nullable<decimal> MaxSal { get; set; }
        public Nullable<decimal> GradePay { get; set; }
        public string Description { get; set; }
        public bool GradeStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public long UserId { get; set; }
        public long CompanyId { get; set; }
        public long BranchId { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
    
}
