//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class GroupMaster
    {
        public long groupID { get; set; }
        public string gID { get; set; }
        public string groupName { get; set; }
        public string GroupType { get; set; }
        public Nullable<int> GrouptypeId { get; set; }
        public long ParentGroupId { get; set; }
        public string SortOrder { get; set; }
        public int fYearID { get; set; }
        public long CompanyId { get; set; }
        public long UserId { get; set; }
        public long BranchId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
    
}
