//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Group
    {
        public Group()
        {
            this.Group1 = new HashSet<Group>();
            this.Products = new HashSet<Product>();
            this.salesusas = new HashSet<salesusa>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<long> ParentGroupId { get; set; }
        public string CategoryTypeId { get; set; }
        public string Fields { get; set; }
        public Nullable<long> RootSerial { get; set; }
        public long UserId { get; set; }
        public long BranchId { get; set; }
        public long CompanyId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<Group> Group1 { get; set; }
        public virtual Group Group2 { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<salesusa> salesusas { get; set; }
    }
    
}
