//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Hatchery_MSTR_Hiss
    {
        public Hatchery_MSTR_Hiss()
        {
            this.Received_Egg_Hiss = new HashSet<Received_Egg_Hiss>();
        }
    
        public long Id { get; set; }
        public string HatcheryName { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Address { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> Branch_Id { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<Received_Egg_Hiss> Received_Egg_Hiss { get; set; }
    }
    
}
