//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class IssueDetail
    {
        public long Id { get; set; }
        public long IssueId { get; set; }
        public long WareHouseId { get; set; }
        public long ProductId { get; set; }
        public Nullable<decimal> QuantityPU { get; set; }
        public Nullable<decimal> QuantitySU { get; set; }
        public decimal UnitFormula { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
    
}
