//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class ItemAdjustment
    {
        public long Id { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<System.DateTime> AdustmentDate { get; set; }
        public string Reason { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> AdjustmentType { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> UserId { get; set; }
    }
    
}
