//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class JournalDetail
    {
        public long Id { get; set; }
        public long JournalId { get; set; }
        public long LID { get; set; }
        public string Particulars { get; set; }
        public string Narrative { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Journal Journal { get; set; }
    }
    
}
