//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Journal
    {
        public Journal()
        {
            this.JournalDetails = new HashSet<JournalDetail>();
        }
    
        public long Id { get; set; }
        public string JournalCode { get; set; }
        public Nullable<int> Category { get; set; }
        public string JournalName { get; set; }
        public string Narration { get; set; }
        public Nullable<System.DateTime> JournalDate { get; set; }
        public long FinancialYearId { get; set; }
        public long CompanyId { get; set; }
        public long UserId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<JournalDetail> JournalDetails { get; set; }
    }
    
}
