//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Leave
    {
        public int LeaveId { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public Nullable<int> MinServicePeriodBeforeLeave { get; set; }
        public Nullable<decimal> MaxLeaveBalance { get; set; }
        public Nullable<decimal> MinInstance { get; set; }
        public Nullable<decimal> MaxInstance { get; set; }
        public string UnavailedLeaveWillLapce { get; set; }
        public string LeaveRequestWindow { get; set; }
        public Nullable<int> NoticeForLeaveRequest { get; set; }
        public string IsLeavePartofHoliday { get; set; }
        public string CanCarryForward { get; set; }
        public Nullable<int> MaxCarryForwardatYearEnd { get; set; }
        public string IsEncashable { get; set; }
        public Nullable<int> MaxDaysEncashable { get; set; }
        public string CreditFrequncy { get; set; }
    }
    
}
