//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class LedgerMaster
    {
        public LedgerMaster()
        {
            this.Costings = new HashSet<Costing>();
            this.DEBankDetails = new HashSet<DEBankDetail>();
            this.DEVoucherDetails = new HashSet<DEVoucherDetail>();
            this.OpeningBalancePayments = new HashSet<OpeningBalancePayment>();
            this.Reconcilations = new HashSet<Reconcilation>();
        }
    
        public long LID { get; set; }
        public string ledgerID { get; set; }
        public string ledgerName { get; set; }
        public int groupID { get; set; }
        public string ledgerType { get; set; }
        public Nullable<long> parentID { get; set; }
        public Nullable<long> TagWith { get; set; }
        public int fYearID { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<Costing> Costings { get; set; }
        public virtual ICollection<DEBankDetail> DEBankDetails { get; set; }
        public virtual ICollection<DEVoucherDetail> DEVoucherDetails { get; set; }
        public virtual ICollection<OpeningBalancePayment> OpeningBalancePayments { get; set; }
        public virtual ICollection<Reconcilation> Reconcilations { get; set; }
    }
    
}
