//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class OpBalancePaymentDetail
    {
        public long Id { get; set; }
        public string Type { get; set; }
        public Nullable<long> OpBalanceId { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<int> ReceiptId { get; set; }
    
        public virtual OpeningBalancePayment OpeningBalancePayment { get; set; }
        public virtual ReceiptPayment ReceiptPayment { get; set; }
    }
    
}
