//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class OpeningBalancePayment
    {
        public OpeningBalancePayment()
        {
            this.OpBalancePaymentDetails = new HashSet<OpBalancePaymentDetail>();
        }
    
        public long Id { get; set; }
        public Nullable<long> Fyear { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<long> LedgerId { get; set; }
        public Nullable<bool> IsPaid { get; set; }
    
        public virtual LedgerMaster LedgerMaster { get; set; }
        public virtual ICollection<OpBalancePaymentDetail> OpBalancePaymentDetails { get; set; }
    }
    
}
