//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class PaymentTerm
    {
        public long Id { get; set; }
        public string PaymentTermDescription { get; set; }
        public Nullable<int> Days { get; set; }
        public long BranchId { get; set; }
        public long CompanyId { get; set; }
        public long UserId { get; set; }
        public bool IsDeleted { get; set; }
    }
    
}
