//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Payroll
    {
        public int PayrollId { get; set; }
        public string EmployeeId { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Payable { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public bool Status { get; set; }
        public string transactionNo { get; set; }
        public string transactionType { get; set; }
    }
    
}
