//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class PayrollDetail
    {
        public int PayrollDetailId { get; set; }
        public int PayrollId { get; set; }
        public string PayName { get; set; }
        public string PayType { get; set; }
        public decimal Amount { get; set; }
    }
    
}
