//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Plant
    {
        public Plant()
        {
            this.Productions = new HashSet<Production>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ContactName { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string AdressName { get; set; }
        public string Address { get; set; }
        public string Suburb { get; set; }
        public string Town { get; set; }
        public string State { get; set; }
        public Nullable<long> CountryId { get; set; }
        public string PIN { get; set; }
        public long EmployeeId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public long Userid { get; set; }
        public long Branchid { get; set; }
        public long Companyid { get; set; }
        public Nullable<long> IsDeleted { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Production> Productions { get; set; }
    }
    
}
