//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class PORequestDetail
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public long ProductId { get; set; }
        public long UnitId { get; set; }
        public long Quantity { get; set; }
    
        public virtual PORequest PORequest { get; set; }
        public virtual Product Product { get; set; }
        public virtual UOM UOM { get; set; }
    }
    
}
