//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class PoultryDailyEntry
    {
        public PoultryDailyEntry()
        {
            this.ImageofChicks = new HashSet<ImageofChick>();
            this.PoultryDailyEntryFeedDetails = new HashSet<PoultryDailyEntryFeedDetail>();
        }
    
        public long Id { get; set; }
        public int FarmId { get; set; }
        public int FlockId { get; set; }
        public System.DateTime StartingDate { get; set; }
        public string StartingDateString { get; set; }
        public System.DateTime Date { get; set; }
        public string DateString { get; set; }
        public Nullable<decimal> AgeOfChicks { get; set; }
        public long OpeningNoOfChicks { get; set; }
        public decimal ChickPrice { get; set; }
        public Nullable<long> Mortality { get; set; }
        public Nullable<long> TotalMortality { get; set; }
        public Nullable<long> SoldCustomerId { get; set; }
        public Nullable<long> SoldChicks { get; set; }
        public Nullable<long> ClosingNoOfChicks { get; set; }
        public Nullable<decimal> TotalBodyWeightOpening { get; set; }
        public Nullable<decimal> LastBodyWeightOpening { get; set; }
        public Nullable<decimal> TotalBodyWeightClosing { get; set; }
        public Nullable<decimal> BodyWeightPerChickStandard { get; set; }
        public Nullable<decimal> BodyWeightPerChickActual { get; set; }
        public Nullable<decimal> ADGActual { get; set; }
        public Nullable<decimal> ADGStandard { get; set; }
        public Nullable<decimal> FCRStandard { get; set; }
        public Nullable<decimal> FCRActual { get; set; }
        public string Remarks { get; set; }
        public string ChicksImage { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string IsSold { get; set; }
    
        public virtual FarmMaster FarmMaster { get; set; }
        public virtual FlockReceivedInFarmMaster FlockReceivedInFarmMaster { get; set; }
        public virtual ICollection<ImageofChick> ImageofChicks { get; set; }
        public virtual ICollection<PoultryDailyEntryFeedDetail> PoultryDailyEntryFeedDetails { get; set; }
    }
    
}
