//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class PriceList
    {
        public long Id { get; set; }
        public long ProductId { get; set; }
        public Nullable<decimal> SPTier1 { get; set; }
        public Nullable<decimal> SPTier2 { get; set; }
        public Nullable<decimal> SPTier3 { get; set; }
        public Nullable<decimal> SPTier4 { get; set; }
        public Nullable<decimal> SPTier5 { get; set; }
        public Nullable<long> BranchId { get; set; }
        public long CompanyId { get; set; }
        public long UserId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Product Product { get; set; }
    }
    
}
