//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Production
    {
        public Production()
        {
            this.ProductionDetails = new HashSet<ProductionDetail>();
        }
    
        public long Id { get; set; }
        public long ProductId { get; set; }
        public Nullable<long> PrimaryUnit { get; set; }
        public Nullable<long> SecondaryUnit { get; set; }
        public Nullable<decimal> QuantityInPU { get; set; }
        public Nullable<decimal> OuantityInSU { get; set; }
        public decimal UnitForm { get; set; }
        public Nullable<long> PlantId { get; set; }
        public Nullable<decimal> GrossInput { get; set; }
        public Nullable<decimal> GrossActualCost { get; set; }
        public Nullable<decimal> GrossFeedProduced { get; set; }
        public Nullable<decimal> PackingSize { get; set; }
        public Nullable<decimal> CostingPerBag { get; set; }
        public Nullable<decimal> OverHead { get; set; }
        public Nullable<decimal> ProcessLossPercent { get; set; }
        public Nullable<decimal> ProcessLossValue { get; set; }
        public Nullable<decimal> Total1 { get; set; }
        public Nullable<decimal> CommissionPercent { get; set; }
        public Nullable<decimal> CommissionValue { get; set; }
        public Nullable<decimal> Total2 { get; set; }
        public Nullable<decimal> SPperBag { get; set; }
        public Nullable<decimal> MarginPLperBag { get; set; }
        public long CompanyId { get; set; }
        public long UserId { get; set; }
        public long BranchId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<ProductionDetail> ProductionDetails { get; set; }
    }
    
}
