//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class ProductOpening
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public long ProductId { get; set; }
        public Nullable<long> UnitId { get; set; }
        public Nullable<long> UnitIdSecondary { get; set; }
        public Nullable<decimal> UOM_Size { get; set; }
        public decimal Opening { get; set; }
        public Nullable<decimal> Price { get; set; }
        public long UserId { get; set; }
        public long Branchid { get; set; }
        public long Companyid { get; set; }
        public int FinancialYearId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual UOM UOM { get; set; }
        public virtual UOM UOM1 { get; set; }
    }
    
}
