//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class ProductionDetail
    {
        public long Id { get; set; }
        public long ProductionId { get; set; }
        public long ProductId { get; set; }
        public Nullable<decimal> QuantityPU { get; set; }
        public Nullable<decimal> QuantitySU { get; set; }
        public decimal UnitFormula { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> CostPerKg { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Production Production { get; set; }
    }
    
}
