//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class ProductCompany
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ContactNumber { get; set; }
        public string EmailId { get; set; }
        public string Address { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string City { get; set; }
        public string StateId { get; set; }
        public string CountryId { get; set; }
        public string Zipcode { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyLogo { get; set; }
        public string VATNumber { get; set; }
        public string TANNO { get; set; }
        public string TIN { get; set; }
        public string PANNO { get; set; }
        public string ContactPerson1 { get; set; }
        public string Designation1 { get; set; }
        public string ContactPerson2 { get; set; }
        public string Designation2 { get; set; }
        public string ContactPerson3 { get; set; }
        public string Designation3 { get; set; }
        public string ContactNumber1 { get; set; }
        public string ContactNumber2 { get; set; }
        public string ContactNumber3 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
    
}
