//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Product
    {
        public Product()
        {
            this.FarmDailyEntryDetails = new HashSet<FarmDailyEntryDetail>();
            this.FarmerReportSalesDetails = new HashSet<FarmerReportSalesDetail>();
            this.FeedDailyEntryDetails = new HashSet<FeedDailyEntryDetail>();
            this.FeedIssueDetails = new HashSet<FeedIssueDetail>();
            this.FeedIssuedFromUnitDetails = new HashSet<FeedIssuedFromUnitDetail>();
            this.FeedReceivedDetails = new HashSet<FeedReceivedDetail>();
            this.FeedRecivedFromFarmDetails = new HashSet<FeedRecivedFromFarmDetail>();
            this.FeedReturnedFromFarmDetails = new HashSet<FeedReturnedFromFarmDetail>();
            this.PORequestDetails = new HashSet<PORequestDetail>();
            this.PoultryDailyEntryFeedDetails = new HashSet<PoultryDailyEntryFeedDetail>();
            this.PriceLists = new HashSet<PriceList>();
            this.PriceList_Log = new HashSet<PriceList_Log>();
            this.ProductCompositions = new HashSet<ProductComposition>();
            this.Productions = new HashSet<Production>();
            this.ProductionDetails = new HashSet<ProductionDetail>();
            this.ProductOpenings = new HashSet<ProductOpening>();
            this.PurchaseInvoiceDetails = new HashSet<PurchaseInvoiceDetail>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.PurchaseReceiptDetails = new HashSet<PurchaseReceiptDetail>();
            this.PurchaseRequestDetails = new HashSet<PurchaseRequestDetail>();
            this.PurchaseReturnDetails = new HashSet<PurchaseReturnDetail>();
            this.Received_Egg_Hiss = new HashSet<Received_Egg_Hiss>();
            this.SalesDeliveryDetails = new HashSet<SalesDeliveryDetail>();
            this.SalesInvoiceDetails = new HashSet<SalesInvoiceDetail>();
            this.SalesOrderDetails = new HashSet<SalesOrderDetail>();
            this.SalesPerformaInvoiceDetails = new HashSet<SalesPerformaInvoiceDetail>();
            this.SalesQuoteDetails = new HashSet<SalesQuoteDetail>();
            this.SalesReturnDetails = new HashSet<SalesReturnDetail>();
            this.Stocks = new HashSet<Stock>();
            this.TransferDeliveryReceiveDetails = new HashSet<TransferDeliveryReceiveDetail>();
            this.UnitDailyEntryDetails = new HashSet<UnitDailyEntryDetail>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public string HSNCode { get; set; }
        public Nullable<long> UnitId { get; set; }
        public Nullable<decimal> UnitFormula { get; set; }
        public Nullable<long> UnitIdSecondary { get; set; }
        public Nullable<long> GroupId { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> MinDiscount { get; set; }
        public Nullable<decimal> MaxDiscount { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public Nullable<long> PurchaseTax { get; set; }
        public Nullable<long> SalesTax { get; set; }
        public Nullable<bool> IsPurchaseProduct { get; set; }
        public bool IsSalesProduct { get; set; }
        public bool IsStockProduct { get; set; }
        public bool IsAssembledProduct { get; set; }
        public bool IsComponentProduct { get; set; }
        public string PickOutProperty { get; set; }
        public string Productimage { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string Colour { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<decimal> CubicTotal { get; set; }
        public long Userid { get; set; }
        public long Branchid { get; set; }
        public long companyid { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> Dose { get; set; }
        public Nullable<long> DoseUnitId { get; set; }
        public Nullable<int> PerBird { get; set; }
        public Nullable<int> RouteId { get; set; }
        public string ReComendesion { get; set; }
        public Nullable<int> ExpiryDurationInMonth { get; set; }
        public Nullable<long> CompositionUnit { get; set; }
        public Nullable<decimal> CompositionQuantity { get; set; }
    
        public virtual ICollection<FarmDailyEntryDetail> FarmDailyEntryDetails { get; set; }
        public virtual ICollection<FarmerReportSalesDetail> FarmerReportSalesDetails { get; set; }
        public virtual ICollection<FeedDailyEntryDetail> FeedDailyEntryDetails { get; set; }
        public virtual ICollection<FeedIssueDetail> FeedIssueDetails { get; set; }
        public virtual ICollection<FeedIssuedFromUnitDetail> FeedIssuedFromUnitDetails { get; set; }
        public virtual ICollection<FeedReceivedDetail> FeedReceivedDetails { get; set; }
        public virtual ICollection<FeedRecivedFromFarmDetail> FeedRecivedFromFarmDetails { get; set; }
        public virtual ICollection<FeedReturnedFromFarmDetail> FeedReturnedFromFarmDetails { get; set; }
        public virtual Group Group { get; set; }
        public virtual ICollection<PORequestDetail> PORequestDetails { get; set; }
        public virtual ICollection<PoultryDailyEntryFeedDetail> PoultryDailyEntryFeedDetails { get; set; }
        public virtual ICollection<PriceList> PriceLists { get; set; }
        public virtual ICollection<PriceList_Log> PriceList_Log { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual Product Product2 { get; set; }
        public virtual Product Product11 { get; set; }
        public virtual Product Product3 { get; set; }
        public virtual ProductCategory_MSTR ProductCategory_MSTR { get; set; }
        public virtual Route Route { get; set; }
        public virtual UOM UOM { get; set; }
        public virtual UOM UOM1 { get; set; }
        public virtual UOM UOM2 { get; set; }
        public virtual UOM UOM3 { get; set; }
        public virtual ICollection<ProductComposition> ProductCompositions { get; set; }
        public virtual ICollection<Production> Productions { get; set; }
        public virtual ICollection<ProductionDetail> ProductionDetails { get; set; }
        public virtual ICollection<ProductOpening> ProductOpenings { get; set; }
        public virtual ICollection<PurchaseInvoiceDetail> PurchaseInvoiceDetails { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual ICollection<PurchaseReceiptDetail> PurchaseReceiptDetails { get; set; }
        public virtual ICollection<PurchaseRequestDetail> PurchaseRequestDetails { get; set; }
        public virtual ICollection<PurchaseReturnDetail> PurchaseReturnDetails { get; set; }
        public virtual ICollection<Received_Egg_Hiss> Received_Egg_Hiss { get; set; }
        public virtual ICollection<SalesDeliveryDetail> SalesDeliveryDetails { get; set; }
        public virtual ICollection<SalesInvoiceDetail> SalesInvoiceDetails { get; set; }
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }
        public virtual ICollection<SalesPerformaInvoiceDetail> SalesPerformaInvoiceDetails { get; set; }
        public virtual ICollection<SalesQuoteDetail> SalesQuoteDetails { get; set; }
        public virtual ICollection<SalesReturnDetail> SalesReturnDetails { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual ICollection<TransferDeliveryReceiveDetail> TransferDeliveryReceiveDetails { get; set; }
        public virtual ICollection<UnitDailyEntryDetail> UnitDailyEntryDetails { get; set; }
    }
    
}
