//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class ProductComposition
    {
        public int Id { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> CompositionId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<long> UnitId { get; set; }
    
        public virtual Composition Composition { get; set; }
        public virtual Product Product { get; set; }
        public virtual UOM UOM { get; set; }
    }
    
}
