//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class ProductCategory_MSTR
    {
        public ProductCategory_MSTR()
        {
            this.FeedDailyEntryDetails = new HashSet<FeedDailyEntryDetail>();
            this.FeedIssueDetails = new HashSet<FeedIssueDetail>();
            this.FeedIssuedFromUnitDetails = new HashSet<FeedIssuedFromUnitDetail>();
            this.FeedReceivedDetails = new HashSet<FeedReceivedDetail>();
            this.FeedRecivedFromFarmDetails = new HashSet<FeedRecivedFromFarmDetail>();
            this.FeedReturnedFromFarmDetails = new HashSet<FeedReturnedFromFarmDetail>();
            this.PoultryDailyEntryFeedDetails = new HashSet<PoultryDailyEntryFeedDetail>();
            this.Products = new HashSet<Product>();
        }
    
        public long Id { get; set; }
        public string CategoryName { get; set; }
        public long BranchId { get; set; }
        public long CompanyId { get; set; }
        public long UserId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual ICollection<FeedDailyEntryDetail> FeedDailyEntryDetails { get; set; }
        public virtual ICollection<FeedIssueDetail> FeedIssueDetails { get; set; }
        public virtual ICollection<FeedIssuedFromUnitDetail> FeedIssuedFromUnitDetails { get; set; }
        public virtual ICollection<FeedReceivedDetail> FeedReceivedDetails { get; set; }
        public virtual ICollection<FeedRecivedFromFarmDetail> FeedRecivedFromFarmDetails { get; set; }
        public virtual ICollection<FeedReturnedFromFarmDetail> FeedReturnedFromFarmDetails { get; set; }
        public virtual ICollection<PoultryDailyEntryFeedDetail> PoultryDailyEntryFeedDetails { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
    
}
