//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class PurchaseInvoice
    {
        public PurchaseInvoice()
        {
            this.BillWisePayments = new HashSet<BillWisePayment>();
            this.PurchaseCostingDetails = new HashSet<PurchaseCostingDetail>();
            this.PurchaseInvoiceDetails = new HashSet<PurchaseInvoiceDetail>();
        }
    
        public long Id { get; set; }
        public string CreatedFrom { get; set; }
        public string OrderNo { get; set; }
        public Nullable<long> ReferenceNo { get; set; }
        public string ReceiptIds { get; set; }
        public string PurchaseOrderNo { get; set; }
        public Nullable<long> PurchaseOrderId { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public string Reference { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<System.DateTime> DespatchDate { get; set; }
        public string DespatchNo { get; set; }
        public string DespatchThrough { get; set; }
        public string DespatchDestination { get; set; }
        public int CurrencyId { get; set; }
        public int TransactionCurrency { get; set; }
        public decimal Currencyrate { get; set; }
        public int FinancialYearId { get; set; }
        public Nullable<long> RecurringSalesId { get; set; }
        public long LID { get; set; }
        public Nullable<int> ApproveStatus { get; set; }
        public Nullable<long> PaymentTermId { get; set; }
        public decimal TaxProduct { get; set; }
        public decimal TaxOther { get; set; }
        public decimal SubTotal { get; set; }
        public decimal RoundOff { get; set; }
        public decimal TotalAddAmount { get; set; }
        public decimal TotalDeductAmount { get; set; }
        public decimal GrandTotal { get; set; }
        public decimal BCGrandTotal { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string NO { get; set; }
        public Nullable<long> InvoiceNo { get; set; }
        public string ReferenceInvoice { get; set; }
        public string Memo { get; set; }
        public string Type { get; set; }
        public long WarehouseId { get; set; }
        public string DeliveryName { get; set; }
        public string StreetPoBox { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string StateRegion { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Status { get; set; }
        public long UserId { get; set; }
        public long CompanyId { get; set; }
        public long BranchId { get; set; }
        public Nullable<bool> IsPaid { get; set; }
    
        public virtual ICollection<BillWisePayment> BillWisePayments { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual ICollection<PurchaseCostingDetail> PurchaseCostingDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual ICollection<PurchaseInvoiceDetail> PurchaseInvoiceDetails { get; set; }
    }
    
}
