//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class PurchaseCostingDetail
    {
        public long Id { get; set; }
        public long PurchaseInvoiceId { get; set; }
        public long CostingId { get; set; }
        public string CostingType { get; set; }
        public string Description { get; set; }
        public long TaxId { get; set; }
        public decimal CurrencyRate { get; set; }
        public decimal TaxPercent { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal CostAmount { get; set; }
    
        public virtual Costing Costing { get; set; }
        public virtual PurchaseInvoice PurchaseInvoice { get; set; }
        public virtual Tax Tax { get; set; }
    }
    
}
