//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class PurchaseRequest
    {
        public PurchaseRequest()
        {
            this.PurchaseRequestDetails = new HashSet<PurchaseRequestDetail>();
        }
    
        public long Id { get; set; }
        public string RequestNo { get; set; }
        public System.DateTime RequestDate { get; set; }
        public System.DateTime ExpectedDate { get; set; }
        public Nullable<long> SerialNo { get; set; }
        public int FinancialYearId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Status { get; set; }
        public long UserId { get; set; }
        public long CompanyId { get; set; }
        public long BranchId { get; set; }
        public string Comments { get; set; }
    
        public virtual ICollection<PurchaseRequestDetail> PurchaseRequestDetails { get; set; }
    }
    
}
