//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class PurchaseReceipt
    {
        public PurchaseReceipt()
        {
            this.PurchaseReceiptDetails = new HashSet<PurchaseReceiptDetail>();
        }
    
        public long Id { get; set; }
        public string CreatedFrom { get; set; }
        public Nullable<long> ReferenceNo { get; set; }
        public string OrderNo { get; set; }
        public long SupplierId { get; set; }
        public string Reference { get; set; }
        public Nullable<long> PurchaseOrderId { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public int CurrencyId { get; set; }
        public int TransactionCurrency { get; set; }
        public decimal Currencyrate { get; set; }
        public int FinancialYearId { get; set; }
        public Nullable<long> RecurringSalesId { get; set; }
        public Nullable<int> ApproveStatus { get; set; }
        public Nullable<long> PaymentTermId { get; set; }
        public Nullable<decimal> TaxTotal { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal GrandTotal { get; set; }
        public decimal BCGrandTotal { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string NO { get; set; }
        public string ReferenceChallan { get; set; }
        public string Memo { get; set; }
        public string Type { get; set; }
        public long WarehouseId { get; set; }
        public string DeliveryName { get; set; }
        public string StreetPoBox { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string StateRegion { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string LorryNo { get; set; }
        public string TagNo { get; set; }
        public Nullable<long> InvoiceNo { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Status { get; set; }
        public long UserId { get; set; }
        public long CompanyId { get; set; }
        public long BranchId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual ICollection<PurchaseReceiptDetail> PurchaseReceiptDetails { get; set; }
    }
    
}
