//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class PurchaseCost
    {
        public long Id { get; set; }
        public string PurchaseId { get; set; }
        public Nullable<int> TaxId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> CostRate { get; set; }
        public Nullable<System.DateTime> CostDate { get; set; }
        public string Comments { get; set; }
        public Nullable<int> BrachId { get; set; }
        public Nullable<long> UserId { get; set; }
    }
    
}
