//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Received_Egg_Hiss
    {
        public Received_Egg_Hiss()
        {
            this.Egg_Setting_Hiss = new HashSet<Egg_Setting_Hiss>();
        }
    
        public long Id { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<long> ModeOfTransport { get; set; }
        public Nullable<long> HatcheryId { get; set; }
        public string Source { get; set; }
        public Nullable<long> Source_Id { get; set; }
        public Nullable<long> FarmFlockId { get; set; }
        public Nullable<long> BreedId { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string ReceivedTime { get; set; }
        public Nullable<long> ReceivedQuantity { get; set; }
        public Nullable<decimal> AvgEggWt { get; set; }
        public Nullable<long> FlockAge { get; set; }
        public bool NewBox { get; set; }
        public Nullable<long> NewBoxQuantity { get; set; }
        public bool OldBox { get; set; }
        public Nullable<long> OldBoxQuantity { get; set; }
        public bool NewTray { get; set; }
        public Nullable<long> NewTrayQuantity { get; set; }
        public bool OldTray { get; set; }
        public Nullable<long> OldTrayQuantity { get; set; }
        public Nullable<long> BrokenShell { get; set; }
        public Nullable<long> SmashedShell { get; set; }
        public Nullable<long> FreshEgg { get; set; }
        public Nullable<long> SettingEggQuantity { get; set; }
        public Nullable<long> InfertileEgg { get; set; }
        public Nullable<int> Branch_Id { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual ICollection<Egg_Setting_Hiss> Egg_Setting_Hiss { get; set; }
        public virtual EggFarm_Flock_Hiss EggFarm_Flock_Hiss { get; set; }
        public virtual EggFarm_MSTR_Hiss EggFarm_MSTR_Hiss { get; set; }
        public virtual Hatchery_MSTR_Hiss Hatchery_MSTR_Hiss { get; set; }
        public virtual Product Product { get; set; }
    }
    
}
