//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class ReceiptPayment
    {
        public ReceiptPayment()
        {
            this.BillWisePayments = new HashSet<BillWisePayment>();
            this.BillWiseReceives = new HashSet<BillWiseReceive>();
            this.OpBalancePaymentDetails = new HashSet<OpBalancePaymentDetail>();
            this.Reconcilations = new HashSet<Reconcilation>();
        }
    
        public int Id { get; set; }
        public System.DateTime RPdate { get; set; }
        public System.DateTime RPDatetime { get; set; }
        public string MoneyReceiptNo { get; set; }
        public Nullable<int> fYearId { get; set; }
        public string RPType { get; set; }
        public Nullable<int> RPCashId { get; set; }
        public Nullable<int> ledgerId { get; set; }
        public string chequeNo { get; set; }
        public Nullable<System.DateTime> chequeDate { get; set; }
        public string chequeDetails { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<bool> IsTCS { get; set; }
        public Nullable<decimal> TCSType { get; set; }
        public string transactionType { get; set; }
        public Nullable<decimal> RPCashAmount { get; set; }
        public Nullable<int> RPBankId { get; set; }
        public Nullable<decimal> RPBankAmount { get; set; }
        public string ModeOfPay { get; set; }
        public string transactionNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> VoucherNo { get; set; }
        public string Prefix { get; set; }
        public string CreditCardNo { get; set; }
        public string ExpirayDate { get; set; }
        public string CardName { get; set; }
        public Nullable<decimal> CreditCardAmt { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string NeftRtgsNo { get; set; }
        public Nullable<decimal> CurrencyAmount { get; set; }
        public bool ReconStatus { get; set; }
        public Nullable<System.DateTime> ReconDate { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsBillWise { get; set; }
    
        public virtual ICollection<BillWisePayment> BillWisePayments { get; set; }
        public virtual ICollection<BillWiseReceive> BillWiseReceives { get; set; }
        public virtual ICollection<OpBalancePaymentDetail> OpBalancePaymentDetails { get; set; }
        public virtual ICollection<Reconcilation> Reconcilations { get; set; }
    }
    
}
