//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Reconcilation
    {
        public long Id { get; set; }
        public int RPId { get; set; }
        public long LID { get; set; }
        public System.DateTime SendDate { get; set; }
        public Nullable<System.DateTime> ClearanceDate { get; set; }
        public string Status { get; set; }
        public long UserId { get; set; }
        public long CompanyId { get; set; }
        public long BranchId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual LedgerMaster LedgerMaster { get; set; }
        public virtual ReceiptPayment ReceiptPayment { get; set; }
    }
    
}
