//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Route
    {
        public Route()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string RouteName { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
    
}
