//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class SalaryComponent
    {
        public int SalaryComponentId { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public string PayType { get; set; }
        public string CalculationType { get; set; }
        public Nullable<decimal> PercentageAmnt { get; set; }
        public string ComponentType { get; set; }
        public string AttendenceDependent { get; set; }
        public string IsActive { get; set; }
    }
    
}
