//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class salesusa
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public long CatId { get; set; }
        public string TransactionType { get; set; }
        public string Ctegory { get; set; }
        public string PayRecMode { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public int FinancialYearId { get; set; }
        public System.DateTime Date { get; set; }
        public string dateString { get; set; }
        public Nullable<decimal> AmountDr { get; set; }
        public Nullable<decimal> AmountCr { get; set; }
        public Nullable<decimal> Retail { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public long UserId { get; set; }
        public long CompanyId { get; set; }
        public Nullable<long> BranchId { get; set; }
    
        public virtual Group Group { get; set; }
    }
    
}
