//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class SalesOrderDetail
    {
        public long Id { get; set; }
        public long SalesOrderId { get; set; }
        public long ItemId { get; set; }
        public string BarCode { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public long UnitId { get; set; }
        public long UnitIdSecondary { get; set; }
        public Nullable<long> SecUnitId { get; set; }
        public decimal UnitFormula { get; set; }
        public Nullable<decimal> SecUnitFormula { get; set; }
        public decimal Price { get; set; }
        public decimal Discount { get; set; }
        public decimal DiscountAmount { get; set; }
        public int AccountId { get; set; }
        public decimal CurrencyRate { get; set; }
        public long TaxId { get; set; }
        public decimal TaxPercent { get; set; }
        public decimal TaxAmount { get; set; }
        public Nullable<int> TaxType { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual Tax Tax { get; set; }
        public virtual UOM UOM { get; set; }
        public virtual UOM UOM1 { get; set; }
        public virtual UOM UOM2 { get; set; }
    }
    
}
