//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class SalesMaster
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> SalesDate { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> PartyId { get; set; }
        public string PartyName { get; set; }
        public int NoOfCratesBox { get; set; }
        public Nullable<decimal> AverageWeightBirds { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public string TagNos { get; set; }
        public byte[] SignatureOfDeliveryMan { get; set; }
        public byte[] SignatureOfFarmer { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
    
}
