//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class SalesReturnTax
    {
        public long Id { get; set; }
        public long SalesReturnId { get; set; }
        public Nullable<long> ItemId { get; set; }
        public Nullable<long> CostId { get; set; }
        public long TaxId { get; set; }
        public decimal Amount { get; set; }
        public decimal CurrencyRate { get; set; }
    }
    
}
