//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class SectionMaster
    {
        public int Id { get; set; }
        public Nullable<int> FarmId { get; set; }
        public string SectionName { get; set; }
        public Nullable<long> Capacity { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Length { get; set; }
    
        public virtual FarmMaster FarmMaster { get; set; }
    }
    
}
