//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class SetSalaryDetail
    {
        public int SetSalaryDetailId { get; set; }
        public Nullable<int> SetSalaryId { get; set; }
        public Nullable<int> SalaryCompID { get; set; }
        public string PayName { get; set; }
        public string PayType { get; set; }
        public string CalculationType { get; set; }
        public Nullable<decimal> Monthly { get; set; }
        public Nullable<decimal> Annualy { get; set; }
    }
    
}
