//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class ShedMaster
    {
        public ShedMaster()
        {
            this.FlockMasters = new HashSet<FlockMaster>();
            this.SalesInvoices = new HashSet<SalesInvoice>();
        }
    
        public int Id { get; set; }
        public string ShedNo { get; set; }
        public int BranchId { get; set; }
        public int CompanyId { get; set; }
        public int UserId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<FlockMaster> FlockMasters { get; set; }
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
    }
    
}
