//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class State
    {
        public State()
        {
            this.EggFarm_MSTR_Hiss = new HashSet<EggFarm_MSTR_Hiss>();
            this.Hatchery_MSTR_Hiss = new HashSet<Hatchery_MSTR_Hiss>();
        }
    
        public int StateId { get; set; }
        public string StateName { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        public virtual ICollection<EggFarm_MSTR_Hiss> EggFarm_MSTR_Hiss { get; set; }
        public virtual ICollection<Hatchery_MSTR_Hiss> Hatchery_MSTR_Hiss { get; set; }
    }
    
}
