//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Stock
    {
        public long StockID { get; set; }
        public long ArticleID { get; set; }
        public System.DateTime TranDate { get; set; }
        public string TranCode { get; set; }
        public decimal Items { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string TransTag { get; set; }
        public long TranId { get; set; }
        public string Comments { get; set; }
        public long WarehouseId { get; set; }
        public long BranchId { get; set; }
        public long CompanyId { get; set; }
        public long UserId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public int fYearID { get; set; }
    
        public virtual Product Product { get; set; }
    }
    
}
