//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class StockData
    {
        public int StockID { get; set; }
        public short ArticleID { get; set; }
        public System.DateTime TranDate { get; set; }
        public string TranCode { get; set; }
        public int Items { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int CurrentItems { get; set; }
        public decimal CurrentValue { get; set; }
    }
    
}
