//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class StockCount
    {
        public int Id { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public string ProductId { get; set; }
        public string Description { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> PackSize { get; set; }
        public Nullable<int> CountQuantity { get; set; }
    }
    
}
