//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Supplier
    {
        public Supplier()
        {
            this.PurchaseInvoices = new HashSet<PurchaseInvoice>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.PurchaseReceipts = new HashSet<PurchaseReceipt>();
            this.PurchaseReturns = new HashSet<PurchaseReturn>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string OrganisationName { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string GstVatNumber { get; set; }
        public string PanNo { get; set; }
        public string TinNo { get; set; }
        public string ServiceTaxNo { get; set; }
        public string Notes { get; set; }
        public bool Taxable { get; set; }
        public long LId { get; set; }
        public Nullable<long> PId { get; set; }
        public string PCode { get; set; }
        public long TaxId { get; set; }
        public long CurrencyId { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string BankAccount { get; set; }
        public Nullable<int> PaymentTerm { get; set; }
        public string Website { get; set; }
        public string PoCountry { get; set; }
        public string PoAddressName { get; set; }
        public string PoStreetPoBox { get; set; }
        public string PoSuburb { get; set; }
        public string PoCity { get; set; }
        public string PoStateRegion { get; set; }
        public string PoPostalCode { get; set; }
        public string AddressName { get; set; }
        public string StreetPoBox { get; set; }
        public string Suburb { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string StateRegion { get; set; }
        public string PostalCode { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public string ContactOfficePhone { get; set; }
        public string ContactWebsite { get; set; }
        public string ContactPhone { get; set; }
        public string ContactFaxNo { get; set; }
        public string ContactMobile { get; set; }
        public string ContactDDINumber { get; set; }
        public string ContactTollFreeNo { get; set; }
        public long UserId { get; set; }
        public long CompanyId { get; set; }
        public long BranchId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual CurrencyRate CurrencyRate { get; set; }
        public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<PurchaseReceipt> PurchaseReceipts { get; set; }
        public virtual ICollection<PurchaseReturn> PurchaseReturns { get; set; }
    }
    
}
