//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Tax
    {
        public Tax()
        {
            this.PurchaseCostingDetails = new HashSet<PurchaseCostingDetail>();
            this.PurchaseInvoiceDetails = new HashSet<PurchaseInvoiceDetail>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.PurchaseReceiptDetails = new HashSet<PurchaseReceiptDetail>();
            this.PurchaseRequestDetails = new HashSet<PurchaseRequestDetail>();
            this.PurchaseReturnDetails = new HashSet<PurchaseReturnDetail>();
            this.SalesCostingDetails = new HashSet<SalesCostingDetail>();
            this.SalesDeliveryDetails = new HashSet<SalesDeliveryDetail>();
            this.SalesInvoiceDetails = new HashSet<SalesInvoiceDetail>();
            this.SalesOrderDetails = new HashSet<SalesOrderDetail>();
            this.SalesPerformaCostingDetails = new HashSet<SalesPerformaCostingDetail>();
            this.SalesPerformaInvoiceDetails = new HashSet<SalesPerformaInvoiceDetail>();
            this.SalesQuoteDetails = new HashSet<SalesQuoteDetail>();
            this.SalesReturnDetails = new HashSet<SalesReturnDetail>();
            this.SalesTaxes = new HashSet<SalesTax>();
            this.Taxrates = new HashSet<Taxrate>();
        }
    
        public long TaxId { get; set; }
        public long LId { get; set; }
        public long UserId { get; set; }
        public long BranchId { get; set; }
        public long CompanyId { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public Nullable<bool> IsIndividual { get; set; }
        public Nullable<bool> Status { get; set; }
        public decimal Rate { get; set; }
        public Nullable<decimal> NetEffective { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<PurchaseCostingDetail> PurchaseCostingDetails { get; set; }
        public virtual ICollection<PurchaseInvoiceDetail> PurchaseInvoiceDetails { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual ICollection<PurchaseReceiptDetail> PurchaseReceiptDetails { get; set; }
        public virtual ICollection<PurchaseRequestDetail> PurchaseRequestDetails { get; set; }
        public virtual ICollection<PurchaseReturnDetail> PurchaseReturnDetails { get; set; }
        public virtual ICollection<SalesCostingDetail> SalesCostingDetails { get; set; }
        public virtual ICollection<SalesDeliveryDetail> SalesDeliveryDetails { get; set; }
        public virtual ICollection<SalesInvoiceDetail> SalesInvoiceDetails { get; set; }
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }
        public virtual ICollection<SalesPerformaCostingDetail> SalesPerformaCostingDetails { get; set; }
        public virtual ICollection<SalesPerformaInvoiceDetail> SalesPerformaInvoiceDetails { get; set; }
        public virtual ICollection<SalesQuoteDetail> SalesQuoteDetails { get; set; }
        public virtual ICollection<SalesReturnDetail> SalesReturnDetails { get; set; }
        public virtual ICollection<SalesTax> SalesTaxes { get; set; }
        public virtual ICollection<Taxrate> Taxrates { get; set; }
    }
    
}
