//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Taxrate
    {
        public long TaxrateId { get; set; }
        public Nullable<long> TaxId { get; set; }
        public long TaxCompId { get; set; }
        public string TaxName { get; set; }
        public decimal Taxrate1 { get; set; }
        public Nullable<bool> IsDependTax { get; set; }
        public Nullable<bool> IsCompoundedTax { get; set; }
        public Nullable<decimal> EffectiveTaxRate { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Tax Tax { get; set; }
    }
    
}
