//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class TransferDeliveryReceiveDetail
    {
        public long Id { get; set; }
        public long TransferDeliveryReceiveId { get; set; }
        public long ItemId { get; set; }
        public string BarCode { get; set; }
        public string Description { get; set; }
        public decimal OrderQuantity { get; set; }
        public decimal TransferQuantity { get; set; }
        public decimal ReceiveQuantity { get; set; }
        public long UnitId { get; set; }
        public long UnitIdSecondary { get; set; }
        public Nullable<long> SecUnitId { get; set; }
        public decimal UnitFormula { get; set; }
        public Nullable<decimal> SecUnitFormula { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TransferDeliveryReceive TransferDeliveryReceive { get; set; }
        public virtual UOM UOM { get; set; }
        public virtual UOM UOM1 { get; set; }
        public virtual UOM UOM2 { get; set; }
    }
    
}
