//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class TransactionUSA
    {
        public TransactionUSA()
        {
            this.TransactionUSADetails = new HashSet<TransactionUSADetail>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public System.DateTime ShiftTime { get; set; }
        public Nullable<decimal> TotalReceipt { get; set; }
        public Nullable<decimal> TotalCashOut { get; set; }
        public Nullable<decimal> TotalNeeded { get; set; }
        public Nullable<decimal> CheckInHand { get; set; }
        public Nullable<decimal> CashInHand { get; set; }
        public Nullable<decimal> BankDeposite { get; set; }
        public Nullable<decimal> OverSort { get; set; }
        public Nullable<decimal> GallonQuantity { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public long FinancialYearId { get; set; }
        public long CompanyId { get; set; }
        public long UserId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<TransactionUSADetail> TransactionUSADetails { get; set; }
    }
    
}
