//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class TransactionUSADetail
    {
        public long ID { get; set; }
        public long TranId { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<long> ParentCatId { get; set; }
        public string Particular { get; set; }
        public string CategoryType { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual CategoryUSA CategoryUSA { get; set; }
        public virtual CategoryUSA CategoryUSA1 { get; set; }
        public virtual TransactionUSA TransactionUSA { get; set; }
    }
    
}
