//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class TransferDeliveryReceive
    {
        public TransferDeliveryReceive()
        {
            this.TransferDeliveryReceiveDetails = new HashSet<TransferDeliveryReceiveDetail>();
        }
    
        public long Id { get; set; }
        public string TransferDeliveryNo { get; set; }
        public Nullable<long> TransferOrderId { get; set; }
        public string TransferOrderNo { get; set; }
        public Nullable<System.DateTime> TransferOrderDate { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public System.DateTime TransferDeliveryDate { get; set; }
        public Nullable<System.DateTime> TransferReceiveDate { get; set; }
        public long FromBranchId { get; set; }
        public long ToBranchId { get; set; }
        public long FromWareHouseId { get; set; }
        public long ToWareHouseId { get; set; }
        public string LorryNo { get; set; }
        public string Transporter { get; set; }
        public string TransporterContact { get; set; }
        public string TagNo { get; set; }
        public int FinancialYearId { get; set; }
        public string Comments { get; set; }
        public Nullable<long> SerialNo { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
        public Nullable<long> ReceivedModifiedBy { get; set; }
        public Nullable<System.DateTime> ReceivedModifiedOn { get; set; }
        public string Status { get; set; }
        public long UserId { get; set; }
        public long CompanyId { get; set; }
        public long BranchId { get; set; }
    
        public virtual ICollection<TransferDeliveryReceiveDetail> TransferDeliveryReceiveDetails { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
    
}
