//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class UnitContractRateMaster
    {
        public UnitContractRateMaster()
        {
            this.ChickRequestHOMasters = new HashSet<ChickRequestHOMaster>();
        }
    
        public int Id { get; set; }
        public string ContractCode { get; set; }
        public string ProductionCostName { get; set; }
        public Nullable<decimal> ChikRateCost { get; set; }
        public string ChickRateType { get; set; }
        public Nullable<decimal> FeedRateCost { get; set; }
        public string FeedRateType { get; set; }
        public Nullable<decimal> MedicineCost { get; set; }
        public string MedicineType { get; set; }
        public Nullable<decimal> OverheadCost { get; set; }
        public string OverheadType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string BonusCode { get; set; }
        public Nullable<decimal> GrowingCharge { get; set; }
        public string GrowingChargeType { get; set; }
        public Nullable<decimal> GrowingChargeFixed { get; set; }
        public string GrowingChargeFixedType { get; set; }
        public Nullable<decimal> RateBonus { get; set; }
        public string RateBonusType { get; set; }
        public Nullable<decimal> ProductionCost { get; set; }
        public string ProductionCostType { get; set; }
        public Nullable<decimal> RateBonusPercentage { get; set; }
        public Nullable<decimal> StandardRate { get; set; }
        public string StandardRateType { get; set; }
        public Nullable<decimal> PerformaneBonus { get; set; }
        public Nullable<decimal> MortalityBonus { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<ChickRequestHOMaster> ChickRequestHOMasters { get; set; }
    }
    
}
