//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Unit
    {
        public int Unitid { get; set; }
        public string Symbol { get; set; }
        public string FormalName { get; set; }
        public Nullable<decimal> NOD { get; set; }
        public int CompanyId { get; set; }
        public int UserId { get; set; }
    }
    
}
