//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class UnitDailyEntry
    {
        public UnitDailyEntry()
        {
            this.UnitDailyEntryDetails = new HashSet<UnitDailyEntryDetail>();
        }
    
        public long Id { get; set; }
        public System.DateTime EntryDate { get; set; }
        public long Serial { get; set; }
        public string No { get; set; }
        public string Remarks { get; set; }
        public int FinancialYearid { get; set; }
        public int BranchId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<UnitDailyEntryDetail> UnitDailyEntryDetails { get; set; }
    }
    
}
