//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class UnitDailyEntryDetail
    {
        public long Id { get; set; }
        public long UnitDailyEntryId { get; set; }
        public long ProductId { get; set; }
        public Nullable<decimal> ProductSize { get; set; }
        public Nullable<decimal> ConsumedQuantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual UnitDailyEntry UnitDailyEntry { get; set; }
    }
    
}
