//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class UOM
    {
        public UOM()
        {
            this.FeedDailyEntryDetails = new HashSet<FeedDailyEntryDetail>();
            this.FeedIssueDetails = new HashSet<FeedIssueDetail>();
            this.FeedIssuedFromUnitDetails = new HashSet<FeedIssuedFromUnitDetail>();
            this.FeedReceivedDetails = new HashSet<FeedReceivedDetail>();
            this.FeedRecivedFromFarmDetails = new HashSet<FeedRecivedFromFarmDetail>();
            this.FeedReturnedFromFarmDetails = new HashSet<FeedReturnedFromFarmDetail>();
            this.PORequestDetails = new HashSet<PORequestDetail>();
            this.PoultryDailyEntryFeedDetails = new HashSet<PoultryDailyEntryFeedDetail>();
            this.Products = new HashSet<Product>();
            this.Products1 = new HashSet<Product>();
            this.Products2 = new HashSet<Product>();
            this.Products3 = new HashSet<Product>();
            this.ProductCompositions = new HashSet<ProductComposition>();
            this.ProductOpenings = new HashSet<ProductOpening>();
            this.ProductOpenings1 = new HashSet<ProductOpening>();
            this.PurchaseInvoiceDetails = new HashSet<PurchaseInvoiceDetail>();
            this.PurchaseInvoiceDetails1 = new HashSet<PurchaseInvoiceDetail>();
            this.PurchaseInvoiceDetails2 = new HashSet<PurchaseInvoiceDetail>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.PurchaseOrderDetails1 = new HashSet<PurchaseOrderDetail>();
            this.PurchaseOrderDetails2 = new HashSet<PurchaseOrderDetail>();
            this.PurchaseReceiptDetails = new HashSet<PurchaseReceiptDetail>();
            this.PurchaseReceiptDetails1 = new HashSet<PurchaseReceiptDetail>();
            this.PurchaseReceiptDetails2 = new HashSet<PurchaseReceiptDetail>();
            this.PurchaseRequestDetails = new HashSet<PurchaseRequestDetail>();
            this.PurchaseRequestDetails1 = new HashSet<PurchaseRequestDetail>();
            this.PurchaseRequestDetails2 = new HashSet<PurchaseRequestDetail>();
            this.PurchaseReturnDetails = new HashSet<PurchaseReturnDetail>();
            this.SalesDeliveryDetails = new HashSet<SalesDeliveryDetail>();
            this.SalesDeliveryDetails1 = new HashSet<SalesDeliveryDetail>();
            this.SalesDeliveryDetails2 = new HashSet<SalesDeliveryDetail>();
            this.SalesInvoiceDetails = new HashSet<SalesInvoiceDetail>();
            this.SalesInvoiceDetails1 = new HashSet<SalesInvoiceDetail>();
            this.SalesInvoiceDetails2 = new HashSet<SalesInvoiceDetail>();
            this.SalesOrderDetails = new HashSet<SalesOrderDetail>();
            this.SalesOrderDetails1 = new HashSet<SalesOrderDetail>();
            this.SalesOrderDetails2 = new HashSet<SalesOrderDetail>();
            this.SalesPerformaInvoiceDetails = new HashSet<SalesPerformaInvoiceDetail>();
            this.SalesPerformaInvoiceDetails1 = new HashSet<SalesPerformaInvoiceDetail>();
            this.SalesPerformaInvoiceDetails2 = new HashSet<SalesPerformaInvoiceDetail>();
            this.SalesQuoteDetails = new HashSet<SalesQuoteDetail>();
            this.SalesQuoteDetails1 = new HashSet<SalesQuoteDetail>();
            this.SalesQuoteDetails2 = new HashSet<SalesQuoteDetail>();
            this.SalesReturnDetails = new HashSet<SalesReturnDetail>();
            this.SalesReturnDetails1 = new HashSet<SalesReturnDetail>();
            this.SalesReturnDetails2 = new HashSet<SalesReturnDetail>();
            this.TransferDeliveryReceiveDetails = new HashSet<TransferDeliveryReceiveDetail>();
            this.TransferDeliveryReceiveDetails1 = new HashSet<TransferDeliveryReceiveDetail>();
            this.TransferDeliveryReceiveDetails2 = new HashSet<TransferDeliveryReceiveDetail>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public long UserId { get; set; }
        public long CompanyId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<FeedDailyEntryDetail> FeedDailyEntryDetails { get; set; }
        public virtual ICollection<FeedIssueDetail> FeedIssueDetails { get; set; }
        public virtual ICollection<FeedIssuedFromUnitDetail> FeedIssuedFromUnitDetails { get; set; }
        public virtual ICollection<FeedReceivedDetail> FeedReceivedDetails { get; set; }
        public virtual ICollection<FeedRecivedFromFarmDetail> FeedRecivedFromFarmDetails { get; set; }
        public virtual ICollection<FeedReturnedFromFarmDetail> FeedReturnedFromFarmDetails { get; set; }
        public virtual ICollection<PORequestDetail> PORequestDetails { get; set; }
        public virtual ICollection<PoultryDailyEntryFeedDetail> PoultryDailyEntryFeedDetails { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Product> Products1 { get; set; }
        public virtual ICollection<Product> Products2 { get; set; }
        public virtual ICollection<Product> Products3 { get; set; }
        public virtual ICollection<ProductComposition> ProductCompositions { get; set; }
        public virtual ICollection<ProductOpening> ProductOpenings { get; set; }
        public virtual ICollection<ProductOpening> ProductOpenings1 { get; set; }
        public virtual ICollection<PurchaseInvoiceDetail> PurchaseInvoiceDetails { get; set; }
        public virtual ICollection<PurchaseInvoiceDetail> PurchaseInvoiceDetails1 { get; set; }
        public virtual ICollection<PurchaseInvoiceDetail> PurchaseInvoiceDetails2 { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails1 { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails2 { get; set; }
        public virtual ICollection<PurchaseReceiptDetail> PurchaseReceiptDetails { get; set; }
        public virtual ICollection<PurchaseReceiptDetail> PurchaseReceiptDetails1 { get; set; }
        public virtual ICollection<PurchaseReceiptDetail> PurchaseReceiptDetails2 { get; set; }
        public virtual ICollection<PurchaseRequestDetail> PurchaseRequestDetails { get; set; }
        public virtual ICollection<PurchaseRequestDetail> PurchaseRequestDetails1 { get; set; }
        public virtual ICollection<PurchaseRequestDetail> PurchaseRequestDetails2 { get; set; }
        public virtual ICollection<PurchaseReturnDetail> PurchaseReturnDetails { get; set; }
        public virtual ICollection<SalesDeliveryDetail> SalesDeliveryDetails { get; set; }
        public virtual ICollection<SalesDeliveryDetail> SalesDeliveryDetails1 { get; set; }
        public virtual ICollection<SalesDeliveryDetail> SalesDeliveryDetails2 { get; set; }
        public virtual ICollection<SalesInvoiceDetail> SalesInvoiceDetails { get; set; }
        public virtual ICollection<SalesInvoiceDetail> SalesInvoiceDetails1 { get; set; }
        public virtual ICollection<SalesInvoiceDetail> SalesInvoiceDetails2 { get; set; }
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails1 { get; set; }
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails2 { get; set; }
        public virtual ICollection<SalesPerformaInvoiceDetail> SalesPerformaInvoiceDetails { get; set; }
        public virtual ICollection<SalesPerformaInvoiceDetail> SalesPerformaInvoiceDetails1 { get; set; }
        public virtual ICollection<SalesPerformaInvoiceDetail> SalesPerformaInvoiceDetails2 { get; set; }
        public virtual ICollection<SalesQuoteDetail> SalesQuoteDetails { get; set; }
        public virtual ICollection<SalesQuoteDetail> SalesQuoteDetails1 { get; set; }
        public virtual ICollection<SalesQuoteDetail> SalesQuoteDetails2 { get; set; }
        public virtual ICollection<SalesReturnDetail> SalesReturnDetails { get; set; }
        public virtual ICollection<SalesReturnDetail> SalesReturnDetails1 { get; set; }
        public virtual ICollection<SalesReturnDetail> SalesReturnDetails2 { get; set; }
        public virtual ICollection<TransferDeliveryReceiveDetail> TransferDeliveryReceiveDetails { get; set; }
        public virtual ICollection<TransferDeliveryReceiveDetail> TransferDeliveryReceiveDetails1 { get; set; }
        public virtual ICollection<TransferDeliveryReceiveDetail> TransferDeliveryReceiveDetails2 { get; set; }
    }
    
}
