//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class UploadImageMaster
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public Nullable<int> FarmId { get; set; }
    
        public virtual FarmMaster FarmMaster { get; set; }
    }
    
}
