//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class User
    {
        public User()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserId { get; set; }
        public string PhoneNumber { get; set; }
        public string UserEmailAddress { get; set; }
        public long RoleId { get; set; }
        public Nullable<int> LID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string ZIP_Code { get; set; }
        public string UserImage { get; set; }
        public Nullable<int> CreatedId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Image { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual Role Role { get; set; }
    }
    
}
