//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class VaccineMaster
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ChequeNo { get; set; }
        public string Particulars { get; set; }
        public Nullable<decimal> Doses { get; set; }
        public Nullable<decimal> Nos { get; set; }
        public string TagNo { get; set; }
        public Nullable<int> ReceivedBottleNos { get; set; }
        public Nullable<decimal> ReceivedBottleSize { get; set; }
        public Nullable<int> IssuedBottleNos { get; set; }
        public Nullable<decimal> IssuedBottleSize { get; set; }
        public Nullable<int> BalanceBottleNos { get; set; }
        public Nullable<decimal> BalanceBottleSize { get; set; }
        public byte[] SignatureOfDeliveryMan { get; set; }
        public byte[] SignatureOfFarmer { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
    
}
