//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class VoucherPolitry
    {
        public int Id { get; set; }
        public Nullable<int> ExpensesHeadMasterID { get; set; }
        public string ExpensesBy { get; set; }
        public string VoucherDate { get; set; }
        public System.DateTime VoucherDatetime { get; set; }
        public Nullable<int> voucherCashId { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string ChequeDetails { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> CashAmount { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<decimal> BankAmount { get; set; }
        public string Remarks { get; set; }
        public string VoucherNo { get; set; }
        public string ChequeName { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public int BranchId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ExpensesHeadMaster ExpensesHeadMaster { get; set; }
    }
    
}
