//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class WarehouseTransfer
    {
        public long Id { get; set; }
        public Nullable<int> SourceWarehouse { get; set; }
        public Nullable<int> DestinationWarehouse { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Comments { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> UserId { get; set; }
    }
    
}
