//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class WarehouseTransferDetail
    {
        public long Id { get; set; }
        public Nullable<int> WarehouseTransferId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Availability { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    }
    
}
