//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace XenERP.Models
{
    public partial class Warehouse
    {
        public Warehouse()
        {
            this.PurchaseInvoices = new HashSet<PurchaseInvoice>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.PurchaseReceipts = new HashSet<PurchaseReceipt>();
            this.PurchaseReturns = new HashSet<PurchaseReturn>();
            this.SalesDeliveries = new HashSet<SalesDelivery>();
            this.SalesInvoices = new HashSet<SalesInvoice>();
            this.SalesOrders = new HashSet<SalesOrder>();
            this.SalesPerformaInvoices = new HashSet<SalesPerformaInvoice>();
            this.SalesQuotes = new HashSet<SalesQuote>();
            this.SalesReturns = new HashSet<SalesReturn>();
            this.TransferDeliveryReceives = new HashSet<TransferDeliveryReceive>();
            this.TransferDeliveryReceives1 = new HashSet<TransferDeliveryReceive>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ContactName { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string DDINumber { get; set; }
        public bool DefaultWarehouse { get; set; }
        public bool Obsolute { get; set; }
        public string AdressName { get; set; }
        public string Address { get; set; }
        public string Suburb { get; set; }
        public string Town { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PIN { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public long Userid { get; set; }
        public long Branchid { get; set; }
        public long Companyid { get; set; }
    
        public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<PurchaseReceipt> PurchaseReceipts { get; set; }
        public virtual ICollection<PurchaseReturn> PurchaseReturns { get; set; }
        public virtual ICollection<SalesDelivery> SalesDeliveries { get; set; }
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
        public virtual ICollection<SalesPerformaInvoice> SalesPerformaInvoices { get; set; }
        public virtual ICollection<SalesQuote> SalesQuotes { get; set; }
        public virtual ICollection<SalesReturn> SalesReturns { get; set; }
        public virtual ICollection<TransferDeliveryReceive> TransferDeliveryReceives { get; set; }
        public virtual ICollection<TransferDeliveryReceive> TransferDeliveryReceives1 { get; set; }
    }
    
}
